// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AddMemberRequestRole.
const (
	AddMemberRequestRoleAdmin  AddMemberRequestRole = "admin"
	AddMemberRequestRoleEditor AddMemberRequestRole = "editor"
)

// Defines values for ChangeMemberRoleRequestRole.
const (
	ChangeMemberRoleRequestRoleAdmin  ChangeMemberRoleRequestRole = "admin"
	ChangeMemberRoleRequestRoleEditor ChangeMemberRoleRequestRole = "editor"
)

// Defines values for FormInviteRole.
const (
	FormInviteRoleEditor FormInviteRole = "editor"
)

// Defines values for MemberRole.
const (
	MemberRoleAdmin  MemberRole = "admin"
	MemberRoleEditor MemberRole = "editor"
)

// Defines values for TicketDetailPriority.
const (
	TicketDetailPriorityHigh   TicketDetailPriority = "High"
	TicketDetailPriorityLow    TicketDetailPriority = "Low"
	TicketDetailPriorityMedium TicketDetailPriority = "Medium"
)

// Defines values for TicketDetailStatus.
const (
	TicketDetailStatusDone       TicketDetailStatus = "done"
	TicketDetailStatusInProgress TicketDetailStatus = "in_progress"
	TicketDetailStatusNew        TicketDetailStatus = "new"
)

// Defines values for TicketSummaryPriority.
const (
	TicketSummaryPriorityHigh   TicketSummaryPriority = "High"
	TicketSummaryPriorityLow    TicketSummaryPriority = "Low"
	TicketSummaryPriorityMedium TicketSummaryPriority = "Medium"
)

// Defines values for TicketSummaryStatus.
const (
	TicketSummaryStatusDone       TicketSummaryStatus = "done"
	TicketSummaryStatusInProgress TicketSummaryStatus = "in_progress"
	TicketSummaryStatusNew        TicketSummaryStatus = "new"
)

// Defines values for UpdateTicketRequestPriority.
const (
	High   UpdateTicketRequestPriority = "High"
	Low    UpdateTicketRequestPriority = "Low"
	Medium UpdateTicketRequestPriority = "Medium"
)

// Defines values for UpdateTicketRequestStatus.
const (
	UpdateTicketRequestStatusDone       UpdateTicketRequestStatus = "done"
	UpdateTicketRequestStatusInProgress UpdateTicketRequestStatus = "in_progress"
	UpdateTicketRequestStatusNew        UpdateTicketRequestStatus = "new"
)

// Defines values for GetV1TicketsParamsStatus.
const (
	GetV1TicketsParamsStatusDone       GetV1TicketsParamsStatus = "done"
	GetV1TicketsParamsStatusInProgress GetV1TicketsParamsStatus = "in_progress"
	GetV1TicketsParamsStatusNew        GetV1TicketsParamsStatus = "new"
)

// AddMemberRequest defines model for AddMemberRequest.
type AddMemberRequest struct {
	Email openapi_types.Email  `json:"email"`
	Role  AddMemberRequestRole `json:"role"`
}

// AddMemberRequestRole defines model for AddMemberRequest.Role.
type AddMemberRequestRole string

// ChangeMemberRoleRequest defines model for ChangeMemberRoleRequest.
type ChangeMemberRoleRequest struct {
	Role ChangeMemberRoleRequestRole `json:"role"`
}

// ChangeMemberRoleRequestRole defines model for ChangeMemberRoleRequest.Role.
type ChangeMemberRoleRequestRole string

// Error defines model for Error.
type Error struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details"`
	Message *string                 `json:"message"`
}

// FormInvite defines model for FormInvite.
type FormInvite struct {
	Code      string             `json:"code"`
	CreatedAt time.Time          `json:"created_at"`
	CreatedBy openapi_types.UUID `json:"created_by"`
	ExpiresAt time.Time          `json:"expires_at"`
	FormId    string             `json:"form_id"`
	Revoked   bool               `json:"revoked"`
	Role      FormInviteRole     `json:"role"`
}

// FormInviteRole defines model for FormInvite.Role.
type FormInviteRole string

// FormQuestion defines model for FormQuestion.
type FormQuestion struct {
	FormId       string    `json:"form_id"`
	Options      *[]string `json:"options"`
	QuestionId   string    `json:"question_id"`
	QuestionType string    `json:"question_type"`
	Title        string    `json:"title"`
}

// FormSummary defines model for FormSummary.
type FormSummary struct {
	FormId string `json:"form_id"`
	Title  string `json:"title"`
}

// ListFormInvitesResponse defines model for ListFormInvitesResponse.
type ListFormInvitesResponse struct {
	Invites []FormInvite `json:"invites"`
}

// ListFormQuestionsResponse defines model for ListFormQuestionsResponse.
type ListFormQuestionsResponse struct {
	Questions []FormQuestion `json:"questions"`
}

// ListFormsResponse defines model for ListFormsResponse.
type ListFormsResponse struct {
	Forms []FormSummary `json:"forms"`
}

// ListMembersResponse defines model for ListMembersResponse.
type ListMembersResponse struct {
	Members []Member `json:"members"`
}

// ListResponsesResponse defines model for ListResponsesResponse.
type ListResponsesResponse struct {
	Responses []Response `json:"responses"`
}

// ListTicketsResponse defines model for ListTicketsResponse.
type ListTicketsResponse struct {
	Tickets []TicketSummary `json:"tickets"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Token string `json:"token"`
}

// Member defines model for Member.
type Member struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
	Role  MemberRole          `json:"role"`
}

// MemberRole defines model for Member.Role.
type MemberRole string

// RegisterFormRequest defines model for RegisterFormRequest.
type RegisterFormRequest struct {
	PollingSec *int `json:"polling_sec,omitempty"`

	// Url Google Forms のURLまたはフォームID
	Url string `json:"url"`
}

// RegisterFormResponse defines model for RegisterFormResponse.
type RegisterFormResponse struct {
	FormId string `json:"form_id"`
}

// Response defines model for Response.
type Response struct {
	CreatedAt     time.Time              `json:"created_at"`
	FormId        string                 `json:"form_id"`
	Payload       map[string]interface{} `json:"payload"`
	ResponseId    string                 `json:"response_id"`
	SchemaVersion int                    `json:"schema_version"`
	SubmittedAt   time.Time              `json:"submitted_at"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// SignupResponse defines model for SignupResponse.
type SignupResponse struct {
	Token string `json:"token"`
}

// SyncResponse defines model for SyncResponse.
type SyncResponse struct {
	// Last 最後に同期された回答の送信時刻（RFC3339形式）または空文字列
	Last *string `json:"last,omitempty"`

	// NewTickets 新規作成されたチケット数
	NewTickets int `json:"newTickets"`

	// Synced 同期された回答数
	Synced int `json:"synced"`
}

// TicketAnswer defines model for TicketAnswer.
type TicketAnswer struct {
	DisplayValue  string   `json:"display_value"`
	QuestionId    string   `json:"question_id"`
	QuestionTitle string   `json:"question_title"`
	QuestionType  string   `json:"question_type"`
	Values        []string `json:"values"`
}

// TicketAssignee defines model for TicketAssignee.
type TicketAssignee struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
}

// TicketDetail defines model for TicketDetail.
type TicketDetail struct {
	Answers         []TicketAnswer       `json:"answers"`
	Assignee        *TicketAssignee      `json:"assignee"`
	FormId          string               `json:"form_id"`
	FormTitle       string               `json:"form_title"`
	Id              openapi_types.UUID   `json:"id"`
	Priority        TicketDetailPriority `json:"priority"`
	ResponseId      string               `json:"response_id"`
	Status          TicketDetailStatus   `json:"status"`
	SubmittedAt     time.Time            `json:"submitted_at"`
	Title           string               `json:"title"`
	TitleQuestionId *string              `json:"title_question_id"`
	UpdatedAt       time.Time            `json:"updated_at"`
}

// TicketDetailPriority defines model for TicketDetail.Priority.
type TicketDetailPriority string

// TicketDetailStatus defines model for TicketDetail.Status.
type TicketDetailStatus string

// TicketSummary defines model for TicketSummary.
type TicketSummary struct {
	Assignee        *TicketAssignee       `json:"assignee"`
	FormId          string                `json:"form_id"`
	FormTitle       string                `json:"form_title"`
	Id              openapi_types.UUID    `json:"id"`
	Priority        TicketSummaryPriority `json:"priority"`
	ResponseId      string                `json:"response_id"`
	Status          TicketSummaryStatus   `json:"status"`
	SubmittedAt     time.Time             `json:"submitted_at"`
	Title           string                `json:"title"`
	TitleQuestionId *string               `json:"title_question_id"`
	UpdatedAt       time.Time             `json:"updated_at"`
}

// TicketSummaryPriority defines model for TicketSummary.Priority.
type TicketSummaryPriority string

// TicketSummaryStatus defines model for TicketSummary.Status.
type TicketSummaryStatus string

// UpdateFormTitleQuestionRequest defines model for UpdateFormTitleQuestionRequest.
type UpdateFormTitleQuestionRequest struct {
	TitleQuestionId *string `json:"title_question_id"`
}

// UpdateTicketRequest defines model for UpdateTicketRequest.
type UpdateTicketRequest struct {
	AssigneeId *openapi_types.UUID          `json:"assignee_id"`
	Priority   *UpdateTicketRequestPriority `json:"priority,omitempty"`
	Status     *UpdateTicketRequestStatus   `json:"status,omitempty"`
}

// UpdateTicketRequestPriority defines model for UpdateTicketRequest.Priority.
type UpdateTicketRequestPriority string

// UpdateTicketRequestStatus defines model for UpdateTicketRequest.Status.
type UpdateTicketRequestStatus string

// UpdateUserProfileRequest defines model for UpdateUserProfileRequest.
type UpdateUserProfileRequest struct {
	DisplayName string `json:"display_name"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
}

// PostV1InvitesAcceptJSONBody defines parameters for PostV1InvitesAccept.
type PostV1InvitesAcceptJSONBody struct {
	Code string `json:"code"`
}

// PatchV1MePasswordJSONBody defines parameters for PatchV1MePassword.
type PatchV1MePasswordJSONBody struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// GetV1ResponsesParams defines parameters for GetV1Responses.
type GetV1ResponsesParams struct {
	// FormId フィルタリング用のフォームID
	FormId *string `form:"form_id,omitempty" json:"form_id,omitempty"`

	// Since 指定時刻以降の回答を取得（RFC3339形式）
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`
}

// GetV1TicketsParams defines parameters for GetV1Tickets.
type GetV1TicketsParams struct {
	// FormId フィルタリング用のフォームID
	FormId *string `form:"form_id,omitempty" json:"form_id,omitempty"`

	// Status フィルタリング用のステータス
	Status *GetV1TicketsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetV1TicketsParamsStatus defines parameters for GetV1Tickets.
type GetV1TicketsParamsStatus string

// PostV1AuthLoginJSONRequestBody defines body for PostV1AuthLogin for application/json ContentType.
type PostV1AuthLoginJSONRequestBody = LoginRequest

// PostV1AuthSignupJSONRequestBody defines body for PostV1AuthSignup for application/json ContentType.
type PostV1AuthSignupJSONRequestBody = SignupRequest

// PostV1FormsJSONRequestBody defines body for PostV1Forms for application/json ContentType.
type PostV1FormsJSONRequestBody = RegisterFormRequest

// PostV1FormsFormIdMembersJSONRequestBody defines body for PostV1FormsFormIdMembers for application/json ContentType.
type PostV1FormsFormIdMembersJSONRequestBody = AddMemberRequest

// PutV1FormsFormIdMembersUserIdJSONRequestBody defines body for PutV1FormsFormIdMembersUserId for application/json ContentType.
type PutV1FormsFormIdMembersUserIdJSONRequestBody = ChangeMemberRoleRequest

// PatchV1FormsFormIdTitleQuestionJSONRequestBody defines body for PatchV1FormsFormIdTitleQuestion for application/json ContentType.
type PatchV1FormsFormIdTitleQuestionJSONRequestBody = UpdateFormTitleQuestionRequest

// PostV1InvitesAcceptJSONRequestBody defines body for PostV1InvitesAccept for application/json ContentType.
type PostV1InvitesAcceptJSONRequestBody PostV1InvitesAcceptJSONBody

// PatchV1MeJSONRequestBody defines body for PatchV1Me for application/json ContentType.
type PatchV1MeJSONRequestBody = UpdateUserProfileRequest

// PatchV1MePasswordJSONRequestBody defines body for PatchV1MePassword for application/json ContentType.
type PatchV1MePasswordJSONRequestBody PatchV1MePasswordJSONBody

// PatchV1TicketsTicketIdJSONRequestBody defines body for PatchV1TicketsTicketId for application/json ContentType.
type PatchV1TicketsTicketIdJSONRequestBody = UpdateTicketRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ヘルスチェック
	// (GET /healthz)
	GetHealthz(c *gin.Context)
	// ログイン
	// (POST /v1/auth/login)
	PostV1AuthLogin(c *gin.Context)
	// サインアップ
	// (POST /v1/auth/signup)
	PostV1AuthSignup(c *gin.Context)
	// フォーム一覧
	// (GET /v1/forms)
	GetV1Forms(c *gin.Context)
	// フォーム登録
	// (POST /v1/forms)
	PostV1Forms(c *gin.Context)
	// 接続検証
	// (GET /v1/forms/{form_id}/health)
	GetV1FormsFormIdHealth(c *gin.Context, formId string)
	// 招待コード一覧取得（admin専用）
	// (GET /v1/forms/{form_id}/invites)
	GetV1FormsFormIdInvites(c *gin.Context, formId string)
	// 招待コード発行（admin専用）
	// (POST /v1/forms/{form_id}/invites)
	PostV1FormsFormIdInvites(c *gin.Context, formId string)
	// 招待コード失効（admin専用）
	// (DELETE /v1/forms/{form_id}/invites/{code})
	DeleteV1FormsFormIdInvitesCode(c *gin.Context, formId string, code string)
	// メンバー一覧取得（admin専用）
	// (GET /v1/forms/{form_id}/members)
	GetV1FormsFormIdMembers(c *gin.Context, formId string)
	// メンバー追加（admin専用）
	// (POST /v1/forms/{form_id}/members)
	PostV1FormsFormIdMembers(c *gin.Context, formId string)
	// メンバー削除（admin専用）
	// (DELETE /v1/forms/{form_id}/members/{user_id})
	DeleteV1FormsFormIdMembersUserId(c *gin.Context, formId string, userId openapi_types.UUID)
	// メンバーロール更新（admin専用）
	// (PUT /v1/forms/{form_id}/members/{user_id})
	PutV1FormsFormIdMembersUserId(c *gin.Context, formId string, userId openapi_types.UUID)
	// フォームの質問一覧取得（admin/editor）
	// (GET /v1/forms/{form_id}/questions)
	GetV1FormsFormIdQuestions(c *gin.Context, formId string)
	// フォーム回答の手動同期（admin/editor）
	// (POST /v1/forms/{form_id}/sync)
	PostV1FormsFormIdSync(c *gin.Context, formId string)
	// タイトル用質問の更新（admin）
	// (PATCH /v1/forms/{form_id}/title-question)
	PatchV1FormsFormIdTitleQuestion(c *gin.Context, formId string)
	// 招待コード受理
	// (POST /v1/invites/accept)
	PostV1InvitesAccept(c *gin.Context)
	// アカウント削除
	// (DELETE /v1/me)
	DeleteV1Me(c *gin.Context)
	// プロフィール取得
	// (GET /v1/me)
	GetV1Me(c *gin.Context)
	// プロフィール更新
	// (PATCH /v1/me)
	PatchV1Me(c *gin.Context)
	// パスワード変更
	// (PATCH /v1/me/password)
	PatchV1MePassword(c *gin.Context)
	// 回答一覧取得（admin/editor）
	// (GET /v1/responses)
	GetV1Responses(c *gin.Context, params GetV1ResponsesParams)
	// チケット一覧取得（admin/editor）
	// (GET /v1/tickets)
	GetV1Tickets(c *gin.Context, params GetV1TicketsParams)
	// チケット詳細取得（admin/editor）
	// (GET /v1/tickets/{ticket_id})
	GetV1TicketsTicketId(c *gin.Context, ticketId openapi_types.UUID)
	// チケット更新（admin/editor）
	// (PATCH /v1/tickets/{ticket_id})
	PatchV1TicketsTicketId(c *gin.Context, ticketId openapi_types.UUID)
	// user_idの取得
	// (GET /v1/whoami)
	GetV1Whoami(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthz(c)
}

// PostV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostV1AuthLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1AuthLogin(c)
}

// PostV1AuthSignup operation middleware
func (siw *ServerInterfaceWrapper) PostV1AuthSignup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1AuthSignup(c)
}

// GetV1Forms operation middleware
func (siw *ServerInterfaceWrapper) GetV1Forms(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Forms(c)
}

// PostV1Forms operation middleware
func (siw *ServerInterfaceWrapper) PostV1Forms(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1Forms(c)
}

// GetV1FormsFormIdHealth operation middleware
func (siw *ServerInterfaceWrapper) GetV1FormsFormIdHealth(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1FormsFormIdHealth(c, formId)
}

// GetV1FormsFormIdInvites operation middleware
func (siw *ServerInterfaceWrapper) GetV1FormsFormIdInvites(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1FormsFormIdInvites(c, formId)
}

// PostV1FormsFormIdInvites operation middleware
func (siw *ServerInterfaceWrapper) PostV1FormsFormIdInvites(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1FormsFormIdInvites(c, formId)
}

// DeleteV1FormsFormIdInvitesCode operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1FormsFormIdInvitesCode(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "code" -------------
	var code string

	err = runtime.BindStyledParameterWithOptions("simple", "code", c.Param("code"), &code, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter code: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteV1FormsFormIdInvitesCode(c, formId, code)
}

// GetV1FormsFormIdMembers operation middleware
func (siw *ServerInterfaceWrapper) GetV1FormsFormIdMembers(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1FormsFormIdMembers(c, formId)
}

// PostV1FormsFormIdMembers operation middleware
func (siw *ServerInterfaceWrapper) PostV1FormsFormIdMembers(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1FormsFormIdMembers(c, formId)
}

// DeleteV1FormsFormIdMembersUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1FormsFormIdMembersUserId(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "user_id" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteV1FormsFormIdMembersUserId(c, formId, userId)
}

// PutV1FormsFormIdMembersUserId operation middleware
func (siw *ServerInterfaceWrapper) PutV1FormsFormIdMembersUserId(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "user_id" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutV1FormsFormIdMembersUserId(c, formId, userId)
}

// GetV1FormsFormIdQuestions operation middleware
func (siw *ServerInterfaceWrapper) GetV1FormsFormIdQuestions(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1FormsFormIdQuestions(c, formId)
}

// PostV1FormsFormIdSync operation middleware
func (siw *ServerInterfaceWrapper) PostV1FormsFormIdSync(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1FormsFormIdSync(c, formId)
}

// PatchV1FormsFormIdTitleQuestion operation middleware
func (siw *ServerInterfaceWrapper) PatchV1FormsFormIdTitleQuestion(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchV1FormsFormIdTitleQuestion(c, formId)
}

// PostV1InvitesAccept operation middleware
func (siw *ServerInterfaceWrapper) PostV1InvitesAccept(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1InvitesAccept(c)
}

// DeleteV1Me operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1Me(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteV1Me(c)
}

// GetV1Me operation middleware
func (siw *ServerInterfaceWrapper) GetV1Me(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Me(c)
}

// PatchV1Me operation middleware
func (siw *ServerInterfaceWrapper) PatchV1Me(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchV1Me(c)
}

// PatchV1MePassword operation middleware
func (siw *ServerInterfaceWrapper) PatchV1MePassword(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchV1MePassword(c)
}

// GetV1Responses operation middleware
func (siw *ServerInterfaceWrapper) GetV1Responses(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1ResponsesParams

	// ------------- Optional query parameter "form_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "form_id", c.Request.URL.Query(), &params.FormId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", c.Request.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter since: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Responses(c, params)
}

// GetV1Tickets operation middleware
func (siw *ServerInterfaceWrapper) GetV1Tickets(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1TicketsParams

	// ------------- Optional query parameter "form_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "form_id", c.Request.URL.Query(), &params.FormId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Tickets(c, params)
}

// GetV1TicketsTicketId operation middleware
func (siw *ServerInterfaceWrapper) GetV1TicketsTicketId(c *gin.Context) {

	var err error

	// ------------- Path parameter "ticket_id" -------------
	var ticketId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "ticket_id", c.Param("ticket_id"), &ticketId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ticket_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1TicketsTicketId(c, ticketId)
}

// PatchV1TicketsTicketId operation middleware
func (siw *ServerInterfaceWrapper) PatchV1TicketsTicketId(c *gin.Context) {

	var err error

	// ------------- Path parameter "ticket_id" -------------
	var ticketId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "ticket_id", c.Param("ticket_id"), &ticketId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ticket_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchV1TicketsTicketId(c, ticketId)
}

// GetV1Whoami operation middleware
func (siw *ServerInterfaceWrapper) GetV1Whoami(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Whoami(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz)
	router.POST(options.BaseURL+"/v1/auth/login", wrapper.PostV1AuthLogin)
	router.POST(options.BaseURL+"/v1/auth/signup", wrapper.PostV1AuthSignup)
	router.GET(options.BaseURL+"/v1/forms", wrapper.GetV1Forms)
	router.POST(options.BaseURL+"/v1/forms", wrapper.PostV1Forms)
	router.GET(options.BaseURL+"/v1/forms/:form_id/health", wrapper.GetV1FormsFormIdHealth)
	router.GET(options.BaseURL+"/v1/forms/:form_id/invites", wrapper.GetV1FormsFormIdInvites)
	router.POST(options.BaseURL+"/v1/forms/:form_id/invites", wrapper.PostV1FormsFormIdInvites)
	router.DELETE(options.BaseURL+"/v1/forms/:form_id/invites/:code", wrapper.DeleteV1FormsFormIdInvitesCode)
	router.GET(options.BaseURL+"/v1/forms/:form_id/members", wrapper.GetV1FormsFormIdMembers)
	router.POST(options.BaseURL+"/v1/forms/:form_id/members", wrapper.PostV1FormsFormIdMembers)
	router.DELETE(options.BaseURL+"/v1/forms/:form_id/members/:user_id", wrapper.DeleteV1FormsFormIdMembersUserId)
	router.PUT(options.BaseURL+"/v1/forms/:form_id/members/:user_id", wrapper.PutV1FormsFormIdMembersUserId)
	router.GET(options.BaseURL+"/v1/forms/:form_id/questions", wrapper.GetV1FormsFormIdQuestions)
	router.POST(options.BaseURL+"/v1/forms/:form_id/sync", wrapper.PostV1FormsFormIdSync)
	router.PATCH(options.BaseURL+"/v1/forms/:form_id/title-question", wrapper.PatchV1FormsFormIdTitleQuestion)
	router.POST(options.BaseURL+"/v1/invites/accept", wrapper.PostV1InvitesAccept)
	router.DELETE(options.BaseURL+"/v1/me", wrapper.DeleteV1Me)
	router.GET(options.BaseURL+"/v1/me", wrapper.GetV1Me)
	router.PATCH(options.BaseURL+"/v1/me", wrapper.PatchV1Me)
	router.PATCH(options.BaseURL+"/v1/me/password", wrapper.PatchV1MePassword)
	router.GET(options.BaseURL+"/v1/responses", wrapper.GetV1Responses)
	router.GET(options.BaseURL+"/v1/tickets", wrapper.GetV1Tickets)
	router.GET(options.BaseURL+"/v1/tickets/:ticket_id", wrapper.GetV1TicketsTicketId)
	router.PATCH(options.BaseURL+"/v1/tickets/:ticket_id", wrapper.PatchV1TicketsTicketId)
	router.GET(options.BaseURL+"/v1/whoami", wrapper.GetV1Whoami)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w8b3MTx/lfRXO/34tkRkF2TGcSvXOdpPE0aVwI6QvG41nr1tKGu9tjb89G8XgmkqbE",
	"BrfQDsYlMCVQQiAejFNop4CBD3NINq/4Cp3dvZPuTnt/ZFviXOsNyHd7z/Pss8//3X0WlRLWTWxAg1pK",
	"cVGxShWoA/5zXFU/h/osJCfgWRtalD0zCTYhoQjyEVAHSGM/5jDRAVWK7pO8QqsmVIqKRQkyyspSXiFY",
	"g/wTw9aV4mkFqDoylLwCVUQxUaa7PmHfwLM2IlBl4z3AHE5nNJ79GpYoQzBRAUYZugRjDUYSvV9KIin4",
	"mBBMuvGVsMrxdbFEhRQgjY8BqooowgbQpnzfUmLDvGLYmgZmGc3i7y68OrQsUOY4IsZGzIRTJpvJJ5jo",
	"k8Y8orCH6ZQIBBSqM4AGJEIFFL5HkQ5lUuF9M1sNfGPbSJUNh+dMRKDVEwo2agapUpIJnMdnoP/dLMYa",
	"BIZMYtPKB2dQB68LKEB8YOIBznVoilqX3zOpRtjoXpm4mWKTfcOHIQp1SzooQnoAIaDK3p91UUchab8X",
	"byQjKKKa7E2IhR3e+VF6n4cRRXHqpK3rgFR7Y1TPFIoPZDR8hiza0STrBLRMbFgSlUJiQGBx/p/AOaWo",
	"/F+hY54Lrm0u+NRzKbxKITo90HH0eRIVQ6HH8N5obItqEpUd8HF0xtDHlqM32jzhSCJNQI4iS7ibGMJ0",
	"MSA1aQJgIlUe2Ci6PIJiKCPekNS0tWElUdcBHUXfl6h0BtIY6qgYkJo2ATDtonrQpeThMjIOIuIxgWUt",
	"YKImGxMPRPuLGLoiGYbPQCMZlRgmg+9K3n5mLExqohffbwDGoSbGgydgGVkUEqbskctpYk1DRnnGgiX2",
	"pwrngK1RpTg20oaIDArLQiVtoolRVokgUzhh5TcYlzWY4wYq59Q2T534zKm9cGo3ndpDp7Hm1O87jW2n",
	"8cPkR0rSxBj85KnE2UC5V4vwXXJUUeD3Et7FOVoTVDUM1KTot4tCz7hEwRUWYWYeEsuNkroX0rJndUR7",
	"m02EjRNBQCccCIDuzLKLrkDUJ1uJk6hs2Gak5KrIMjVQnTGALg+19mipdGR8Bo0yrSjFD/K92q18kKy4",
	"afXNjp2sGqVo8BoQzAzqcOvGt80Xq05to3l5tXXjplNbc+qrTu1m8/rfdx5ccWqbr7+tvXp5q3Wt3lx+",
	"9mZ7+cQnE2NjYx82n99ubl96s73SVvid+09bV79rPlhvLq/LOG3AhS87ni1ExNWt3buXXj2/0Vq+3KbA",
	"adSc+i9Oo+E0lltrW4rMLFlVoySSmCBA6WTkQELcdSEG6JXxWrwbN6wFmefwZGEeaDaMTxgSE4qIqDxN",
	"zsHRJ2Q+qaLTUEYiT0ba+PKh+cfwz7JQ2YCwv0qeyjnLPG2ACA9l9Gw+4lUNbtY17Ys5pXi6t8gtzAPA",
	"pavXSNCVyaSl9YB3T2e6PaHINBL41q2XubbXe2k6nHMn+Ez+LloXUsZfJkGYIFr1x2CfonJFYUGgimxd",
	"YdHmgiQQS+F9KaC25YdswAUlryBjxiS4TKDFNQMbUAp+L445Omd338yEzExCkSyv2KYK9hUchGIC37Ll",
	"Q4GDyy/fonSqHKFQwkeVTPtO8dcsRPySfe/l3pEBxF5YsxSJV0h2JDJPVWbkIpq4IvsR2X2JZPSMT1mQ",
	"TBE8h2JKzQn2OyQ1ibGTD2VGfYUHMWEqbFVgyWYrepKZRjGDWQgIJOM2iz3djQhekuWPO/grlJrKEoOB",
	"jDncHfaMT03mVFyydWhQwJ7l5jDJ0YrI0UBufGqyrWRFxf+snTMoI8dGjr0v6qbQACZSisrYsZFjYzzY",
	"pRVObqECgUYr37DfZchXn60HRzmpsswQ0k/dIflgueX9kRFRSjcoNPiXFJ6jBVMDyOhswnCRPQd0kxOK",
	"z0iWgO8i+Cf/xW8D3FWKp6eZIXE9mOI0/uY0Npz6Ex5X/sTiyvpD/kVhfrQAbFopaLgsiDCxJZnUFLbo",
	"V6NskXhBQhFCAC36a6xWQ5MCpqmhEv+28LWFQ1OLc5SBIsxSUNRcP5nA0H3j9mpdch7nleMHiFLsHElQ",
	"fQU0pAohhmIMQzzaf8STxjxDnSsRqEKDIqBZDPevBjHpSYNCYgAtZ0EyD4k381ixfuDUt5z6HafxKCjN",
	"Fk8304izSEz7JM/BZH7AAh1KubMo0R/2H/HHzDXlgEYgUKs5eA5ZNNMiXf+XkGenfpun/+ttwW5vdkR5",
	"na9GeTVS6aeR7NqTiRGrAdirUwZTd0zQN1DNwqr6TFOnBPzqP9/u3v2Jx7Mxxqizdgdvh2RF8VTWaLRP",
	"JEQLz4Qoj/7vu9qw6B4fGes/0k8wmUWqCg2B8fhAMOpWzsA0N4dtI7tKunPt2evVfwaNbWHRTeaX3KA/",
	"hfXlm/SqSAB42kCADimvZJ1eVFiIzVMJlv3yjM1/YCSgjHkfB8Lx//Q+TfxbOBeRKTcx1LWB61rrzz/u",
	"/Pv71p0bu/e2I7XMdyImlZq5R2wyq2dpQqnwMaGjrCm5d/ihgBzBGsx5y/RutuT44vXmiz869UfcbayI",
	"2K556Wrzxfqb7WVOfnOrvnPl3pvtlVQh39uS5NF9eIyIw6DpzpkmxHxDIc+ckO9ce7p7a1Ui3vFmvLDI",
	"JGBJlGo1KE4VB/XgI/5cpgkT4jhtf7QhL4XknuDdj1Id765L/w7nJtwFPeryPZAgSMhPVqOgoGI17/zS",
	"vPAkvWL5jpWmio/cc6qHNj4Kn7MdxkaZdhtO45bTeOQ0LjuN7YMKjAYiwgdfceu6RJW+3Dashx09p3XK",
	"giSzRbKOUu++fN688EPP/qqwaFuQsCc9xoKu8jPuTKrKXqKtocYM/REX3ebKhdfX7sg90QBzDFcRYiEl",
	"HcCZziumLfOdNk3QnoP3c1HXb9PvdR+9QxZDve1Bb53GA/7vRuv649bVrfS+J3B3MVW21L4Qeajryd3X",
	"OodZk1EQl8yyLfSdzUintrn76Ofm2iVZFuXOJU72rapRSjr85BP8k2z4YZT5wKUfCd/FVZjm5uqrp+eH",
	"Ap9hgW/fuGqtXGxeXBPr1oPA813n9876eyQAWqpIZJ89Dgh/4Nj8YSszJJz+TxWFSbIoAXZYdBiGYk79",
	"JT+PuOw0Nnau3BNeielpIBrzq6a3+QNKJWjSJC/k7vaMi8F7V5ID3p/cg84c7crDW9rYGcgR4nH38LDe",
	"btJxfHRkYPMV/YPUHHPmbo+gLO9oXVrfuXy+bQzEnaSkit/nUDkkO6kZssu3nfqGU7/LE+VlUd1iFEZn",
	"ujIuH9xs/JfUspZwHvUC/jovoqw59X+IUorIJ0XpMy5K/hwq/QxbJVcpB3xFJqXQDl35UdYWEer6XFrB",
	"3zglSYOmOk1SDii2tQmBBp2J6TPFG3jM7LW9SxeCELhhxHxYEs0JsZI5b+lyyChhQtxr5RlSub/wq8kP",
	"vUNRK63rj9v6FpCj6Oim3fquu4QTpMhT7Q2W2jZ+5lfttnau3HNqm119u3jx56wNSVVW/Ynd+ws1+Vn9",
	"rrn5vWgk9OrZj6+v/cmpbbpFr/pf2/XdcIOhCBIsZJSgIt0yjGtW0e/dh+7ug9nyqbl3kHu9mTMwJ5j2",
	"7rAwnLGak9CLlFsfvo6R0cbBa2aVRdMQh5RZxfMMaf2lU38SZQ28XjK+9hF76HjSb+sQ7v053JU8HJs0",
	"nUZ0vWlkYVH88I59JWqn+I+fVEneg2nD3u9Jmr7JfKAtWlYdYZuNQ2f4Fk59ChHxJ8KRurd7/9HO461o",
	"3Usq5bxlHetXCSnYf2zA1aMMa/hQjTPsR4N7pxIPulDBQEfxTvMPYsyBNgLwDqcm7px6A9Ne8w+wwv2Y",
	"JcBuHTrUECfYEu70NDMhgrXCVPF+3LwfXLFQ0HAJaBVs0eIHIx+MKEvTS/8NAAD//1XKlQ7bZgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
