// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AddMemberRequestRole.
const (
	AddMemberRequestRoleAdmin  AddMemberRequestRole = "admin"
	AddMemberRequestRoleEditor AddMemberRequestRole = "editor"
)

// Defines values for ChangeMemberRoleRequestRole.
const (
	ChangeMemberRoleRequestRoleAdmin  ChangeMemberRoleRequestRole = "admin"
	ChangeMemberRoleRequestRoleEditor ChangeMemberRoleRequestRole = "editor"
)

// Defines values for MemberRole.
const (
	Admin  MemberRole = "admin"
	Editor MemberRole = "editor"
)

// Defines values for TicketStatus.
const (
	TicketStatusDone       TicketStatus = "done"
	TicketStatusInProgress TicketStatus = "in_progress"
	TicketStatusNew        TicketStatus = "new"
)

// Defines values for UpdateTicketRequestStatus.
const (
	UpdateTicketRequestStatusDone       UpdateTicketRequestStatus = "done"
	UpdateTicketRequestStatusInProgress UpdateTicketRequestStatus = "in_progress"
	UpdateTicketRequestStatusNew        UpdateTicketRequestStatus = "new"
)

// Defines values for GetV1TicketsParamsStatus.
const (
	Done       GetV1TicketsParamsStatus = "done"
	InProgress GetV1TicketsParamsStatus = "in_progress"
	New        GetV1TicketsParamsStatus = "new"
)

// AddMemberRequest defines model for AddMemberRequest.
type AddMemberRequest struct {
	Email openapi_types.Email  `json:"email"`
	Role  AddMemberRequestRole `json:"role"`
}

// AddMemberRequestRole defines model for AddMemberRequest.Role.
type AddMemberRequestRole string

// ChangeMemberRoleRequest defines model for ChangeMemberRoleRequest.
type ChangeMemberRoleRequest struct {
	Role   ChangeMemberRoleRequestRole `json:"role"`
	UserId openapi_types.UUID          `json:"user_id"`
}

// ChangeMemberRoleRequestRole defines model for ChangeMemberRoleRequest.Role.
type ChangeMemberRoleRequestRole string

// Error defines model for Error.
type Error struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details"`
	Message *string                 `json:"message"`
}

// FormSummary defines model for FormSummary.
type FormSummary struct {
	FormId string `json:"form_id"`
	Title  string `json:"title"`
}

// ListFormsResponse defines model for ListFormsResponse.
type ListFormsResponse struct {
	Forms []FormSummary `json:"forms"`
}

// ListMembersResponse defines model for ListMembersResponse.
type ListMembersResponse struct {
	Members []Member `json:"members"`
}

// ListTicketsResponse defines model for ListTicketsResponse.
type ListTicketsResponse struct {
	Tickets []Ticket `json:"tickets"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Token string `json:"token"`
}

// Member defines model for Member.
type Member struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
	Role  MemberRole          `json:"role"`
}

// MemberRole defines model for Member.Role.
type MemberRole string

// RegisterFormRequest defines model for RegisterFormRequest.
type RegisterFormRequest struct {
	PollingSec *int `json:"polling_sec,omitempty"`

	// Url Google Forms のURLまたはフォームID
	Url string `json:"url"`
}

// RegisterFormResponse defines model for RegisterFormResponse.
type RegisterFormResponse struct {
	FormId string `json:"form_id"`
}

// SyncResponse defines model for SyncResponse.
type SyncResponse struct {
	// Last 最後に同期された回答の送信時刻（RFC3339形式）または空文字列
	Last *string `json:"last,omitempty"`

	// NewTickets 新規作成されたチケット数
	NewTickets int `json:"newTickets"`

	// Synced 同期された回答数
	Synced int `json:"synced"`
}

// Ticket defines model for Ticket.
type Ticket struct {
	AssigneeId *openapi_types.UUID `json:"assignee_id"`
	CreatedAt  time.Time           `json:"created_at"`
	FormId     string              `json:"form_id"`
	Id         openapi_types.UUID  `json:"id"`
	Priority   int                 `json:"priority"`
	ResponseId string              `json:"response_id"`
	Status     TicketStatus        `json:"status"`
	UpdatedAt  time.Time           `json:"updated_at"`
}

// TicketStatus defines model for Ticket.Status.
type TicketStatus string

// UpdateTicketRequest defines model for UpdateTicketRequest.
type UpdateTicketRequest struct {
	AssigneeId *openapi_types.UUID        `json:"assignee_id"`
	Status     *UpdateTicketRequestStatus `json:"status,omitempty"`
}

// UpdateTicketRequestStatus defines model for UpdateTicketRequest.Status.
type UpdateTicketRequestStatus string

// DeleteV1FormsFormIdMembersParams defines parameters for DeleteV1FormsFormIdMembers.
type DeleteV1FormsFormIdMembersParams struct {
	UserId openapi_types.UUID `form:"user_id" json:"user_id"`
}

// GetV1TicketsParams defines parameters for GetV1Tickets.
type GetV1TicketsParams struct {
	// FormId フィルタリング用のフォームID
	FormId *string `form:"form_id,omitempty" json:"form_id,omitempty"`

	// Status フィルタリング用のステータス
	Status *GetV1TicketsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetV1TicketsParamsStatus defines parameters for GetV1Tickets.
type GetV1TicketsParamsStatus string

// PostV1AuthLoginJSONRequestBody defines body for PostV1AuthLogin for application/json ContentType.
type PostV1AuthLoginJSONRequestBody = LoginRequest

// PostV1FormsJSONRequestBody defines body for PostV1Forms for application/json ContentType.
type PostV1FormsJSONRequestBody = RegisterFormRequest

// PatchV1FormsFormIdMembersJSONRequestBody defines body for PatchV1FormsFormIdMembers for application/json ContentType.
type PatchV1FormsFormIdMembersJSONRequestBody = ChangeMemberRoleRequest

// PostV1FormsFormIdMembersJSONRequestBody defines body for PostV1FormsFormIdMembers for application/json ContentType.
type PostV1FormsFormIdMembersJSONRequestBody = AddMemberRequest

// PatchV1TicketsTicketIdJSONRequestBody defines body for PatchV1TicketsTicketId for application/json ContentType.
type PatchV1TicketsTicketIdJSONRequestBody = UpdateTicketRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ヘルスチェック
	// (GET /healthz)
	GetHealthz(c *gin.Context)
	// ログイン
	// (POST /v1/auth/login)
	PostV1AuthLogin(c *gin.Context)
	// フォーム一覧
	// (GET /v1/forms)
	GetV1Forms(c *gin.Context)
	// フォーム登録
	// (POST /v1/forms)
	PostV1Forms(c *gin.Context)
	// 接続検証
	// (GET /v1/forms/{form_id}/health)
	GetV1FormsFormIdHealth(c *gin.Context, formId string)
	// メンバー削除（admin専用）
	// (DELETE /v1/forms/{form_id}/members)
	DeleteV1FormsFormIdMembers(c *gin.Context, formId string, params DeleteV1FormsFormIdMembersParams)
	// メンバー一覧取得（admin専用）
	// (GET /v1/forms/{form_id}/members)
	GetV1FormsFormIdMembers(c *gin.Context, formId string)
	// メンバーロール変更（admin専用）
	// (PATCH /v1/forms/{form_id}/members)
	PatchV1FormsFormIdMembers(c *gin.Context, formId string)
	// メンバー追加（admin専用）
	// (POST /v1/forms/{form_id}/members)
	PostV1FormsFormIdMembers(c *gin.Context, formId string)
	// フォーム回答の手動同期（admin/editor）
	// (POST /v1/forms/{form_id}/sync)
	PostV1FormsFormIdSync(c *gin.Context, formId string)
	// チケット一覧取得（admin/editor）
	// (GET /v1/tickets)
	GetV1Tickets(c *gin.Context, params GetV1TicketsParams)
	// チケット詳細取得（admin/editor）
	// (GET /v1/tickets/{ticket_id})
	GetV1TicketsTicketId(c *gin.Context, ticketId openapi_types.UUID)
	// チケット更新（admin/editor）
	// (PATCH /v1/tickets/{ticket_id})
	PatchV1TicketsTicketId(c *gin.Context, ticketId openapi_types.UUID)
	// user_idの取得
	// (GET /v1/whoami)
	GetV1Whoami(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthz(c)
}

// PostV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostV1AuthLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1AuthLogin(c)
}

// GetV1Forms operation middleware
func (siw *ServerInterfaceWrapper) GetV1Forms(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Forms(c)
}

// PostV1Forms operation middleware
func (siw *ServerInterfaceWrapper) PostV1Forms(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1Forms(c)
}

// GetV1FormsFormIdHealth operation middleware
func (siw *ServerInterfaceWrapper) GetV1FormsFormIdHealth(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1FormsFormIdHealth(c, formId)
}

// DeleteV1FormsFormIdMembers operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1FormsFormIdMembers(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteV1FormsFormIdMembersParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := c.Query("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument user_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "user_id", c.Request.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteV1FormsFormIdMembers(c, formId, params)
}

// GetV1FormsFormIdMembers operation middleware
func (siw *ServerInterfaceWrapper) GetV1FormsFormIdMembers(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1FormsFormIdMembers(c, formId)
}

// PatchV1FormsFormIdMembers operation middleware
func (siw *ServerInterfaceWrapper) PatchV1FormsFormIdMembers(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchV1FormsFormIdMembers(c, formId)
}

// PostV1FormsFormIdMembers operation middleware
func (siw *ServerInterfaceWrapper) PostV1FormsFormIdMembers(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1FormsFormIdMembers(c, formId)
}

// PostV1FormsFormIdSync operation middleware
func (siw *ServerInterfaceWrapper) PostV1FormsFormIdSync(c *gin.Context) {

	var err error

	// ------------- Path parameter "form_id" -------------
	var formId string

	err = runtime.BindStyledParameterWithOptions("simple", "form_id", c.Param("form_id"), &formId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1FormsFormIdSync(c, formId)
}

// GetV1Tickets operation middleware
func (siw *ServerInterfaceWrapper) GetV1Tickets(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1TicketsParams

	// ------------- Optional query parameter "form_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "form_id", c.Request.URL.Query(), &params.FormId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Tickets(c, params)
}

// GetV1TicketsTicketId operation middleware
func (siw *ServerInterfaceWrapper) GetV1TicketsTicketId(c *gin.Context) {

	var err error

	// ------------- Path parameter "ticket_id" -------------
	var ticketId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "ticket_id", c.Param("ticket_id"), &ticketId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ticket_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1TicketsTicketId(c, ticketId)
}

// PatchV1TicketsTicketId operation middleware
func (siw *ServerInterfaceWrapper) PatchV1TicketsTicketId(c *gin.Context) {

	var err error

	// ------------- Path parameter "ticket_id" -------------
	var ticketId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "ticket_id", c.Param("ticket_id"), &ticketId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ticket_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchV1TicketsTicketId(c, ticketId)
}

// GetV1Whoami operation middleware
func (siw *ServerInterfaceWrapper) GetV1Whoami(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Whoami(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz)
	router.POST(options.BaseURL+"/v1/auth/login", wrapper.PostV1AuthLogin)
	router.GET(options.BaseURL+"/v1/forms", wrapper.GetV1Forms)
	router.POST(options.BaseURL+"/v1/forms", wrapper.PostV1Forms)
	router.GET(options.BaseURL+"/v1/forms/:form_id/health", wrapper.GetV1FormsFormIdHealth)
	router.DELETE(options.BaseURL+"/v1/forms/:form_id/members", wrapper.DeleteV1FormsFormIdMembers)
	router.GET(options.BaseURL+"/v1/forms/:form_id/members", wrapper.GetV1FormsFormIdMembers)
	router.PATCH(options.BaseURL+"/v1/forms/:form_id/members", wrapper.PatchV1FormsFormIdMembers)
	router.POST(options.BaseURL+"/v1/forms/:form_id/members", wrapper.PostV1FormsFormIdMembers)
	router.POST(options.BaseURL+"/v1/forms/:form_id/sync", wrapper.PostV1FormsFormIdSync)
	router.GET(options.BaseURL+"/v1/tickets", wrapper.GetV1Tickets)
	router.GET(options.BaseURL+"/v1/tickets/:ticket_id", wrapper.GetV1TicketsTicketId)
	router.PATCH(options.BaseURL+"/v1/tickets/:ticket_id", wrapper.PatchV1TicketsTicketId)
	router.GET(options.BaseURL+"/v1/whoami", wrapper.GetV1Whoami)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbX48TyRH/KqNOHjjJwd5bIl38RriQrHJJ0HKQB7RCvTO1dh8z3UN3D5xvZQnb0mX3",
	"bhV44E8IKNwl5A6C2NsEFIW7BT5MY+/yxFeIuntsjz0ztsn+wYR98Y5nu6t+VV2/6uo/XkYuC0JGgUqB",
	"ystIuFUIsHk86nm/gWAR+Dycj0BI/S7kLAQuCZgWEGDi64clxgMsUTl+U0CyFgIqIyE5oRVULyDOfDBd",
	"aBSg8hmEvYBQVEDgEck4Wkh10X3gfEQ4eLp9V7CR02/NFj8BV2oFx6qYViAGzHzIBf3aSAooEsDPEm/A",
	"0igiHhqHuttxBO5fcM54GqXLPIMyhcUDiYlv2mDPI5Iwiv0Tib6SR1BANPJ9vKgttd9TegMQAleMjpy2",
	"OTYZZFmWHGc8OBkFAea1tD3ab7ELUyZJIv0sY4cUd0V0O2Rh+IgIqXGIeRAhowKykZgHIsE+/JjDEiqj",
	"HxX7VCjGPCgmjar3FGLOcS0ToMiFZUNzBLDANpgYmhU4FlVXbB6uj4l7DuQIXNI2mBiXFTgWV1dsJi5W",
	"IXQ30k6IhbjIuDc+uroiej1G4Mr1FDsHdLwq2yxLfjykO7F4ojS183xspI5NyvNQIUIC1yzKHc6Q+T6h",
	"lbMCXP3VgyUc+RKVZ0s9iYRKqNhYj7hvWwmXk1CnP1RGv2Ss4oNjmO+oxvqp+Y9U45lq3FGN71Trmmre",
	"V61N1fpq7sPxKZv7E5gyKrlkp7mcZJal6mSNuvkqfGydOOiBzu1L7WdrqvGgfWWtc/uOalxTzTXVuNO+",
	"9Zeth1dVY/3lpcaL5193bjbbKz+82lyZP35sdnb2Z+2nf21vXn61udpz19b97zvX/9B+eKO9ciMrcChc",
	"/LifEIZAXN/Y/ubyi6e3OytXeghUq6Ga/1StlmqtdK5toKxBFTXqgpcWmGlMtpAh/8YSB/Bm+TpOVikv",
	"YyFIhQLkTPtjpswCcjlgCd5ZLAe6e1jCTyQJIMu1o+bICWkdcsI4kbWEjISbeRxUeUqExDISybRA4SIq",
	"IELPhpxVOAiBCshjFLLLpNB7TZuzkkp/mk/C7YFL2Djg5QH1WSN9yvzbjnduLtrpsO/Ig/UUai0R3Ehb",
	"e1LPrhbkImAO/Ggkq72KXXeyr/tOrkoZorqWQegSS5Pr6Ik5x2NuFACVWL9zlhh3ZNXmUewcPTHXq7XK",
	"KPnuAnBhZZQOlw6/rw1nIVAcElRGs4dLh2fNRCqrBm6xCtiX1c/0c8VyTbvcqJzzdPYG+au4SX/QTdf3",
	"SyVbDFMJ1PSU8Kkshj4mtL9aMe7+FAehAcrOZcSZKZyTxv/u1wPeReUzCwUkutUrUq0/qdYD1Xxiste3",
	"Ons1vzM9ihdmijiS1aKvawE7f4kMo04wIU/P6EEyRQOykQ5C/px5tSGjcBj6xDV9i58INmTaqFproFCq",
	"D/JJh2h9rEN3rDuep3J8XEBHdlGlXSxlqDqNfeLZIAbbRiue2XvFc/SCVu24HDygkmBfaN0/3Q+j56gE",
	"TrHvCOAXgHctHxnWD1VzQzXvqtajXjT3FkR55Dw9YwortJexlFq3jYinfRjWU1RznHHyGXjTMJ6JEexX",
	"sy/+c2n7m2/NtD8iBfXHbvfTT1Z9P1EWmtkjCPnBc8yWCv//GWk4dI+UZvde6XHGF4nnAbUaj+yLxkA4",
	"lElniUV0ekm6dfOHl2v/Gky2xeW4yK3HtdEE2Vd/zHm2TjLVFccBSLNfdGYZ6UrEVFy6SMWmHEzW0Uky",
	"FhIeGC6TFnaY4t/Ant9UTRMHXNt3rnX++Petf/+5c/f29r3NXJYltlY98EFCmmkfmvcDZIt3bPeMbYVY",
	"0vkIeK0vKnFokCtq3DFEmshH0gvA3zLnWDx+b2pWdA4FRAhCK05s9XvvCHedQ2bH1eHMB6c7zu9N2Sz2",
	"tWo9Uq0rqrXZXv3i5c27rzZXDOr2RnPr6r1Xm6sa70Tz1l5TaWGP1ybDhzfv8rTzloWuXSW1L19vP7uR",
	"GcAhlm41Y/WkX+9/EO/+Ii3vZHzy7aJ3b1vngGGvwTDVemg+H7TvrnZuPc4m2bgdireaYqmrMpNvghzs",
	"UkwVwfZlPXVKAJ/arYs+r7efP21/8VUGnXNWWaJG3XEHIgmun9TN38aCcOB8PsPP9tS6vb724vvP3y1C",
	"Fe31kemeuPp7c73LEZ3VL9tfXrPj1o332JZkwCduQuWverq3DVKRPYjV4PibOWR8rlr/0KRrbmxdvaca",
	"66kbK1m7BH1SjNxgmFxp84lqfa6VNp+r5pMcrb1D+MTJ6/9w0L3Xy7XhO20Hh0k5XOhfzclaJuVToLhs",
	"H3Ten4gO9s+cN1HC78ne5T2w3XN7947jVB16O4dIfBrdc6BjnfQmd9X2oZ6yo5GsqHLDfPv+o63HG/lh",
	"Pm474A2H8+4vXbKuRe3zRZKpJNPB7DBwcfPW4871jRHzwsUqwwEZPRX83rbZ1TPGxE8zJvspxqQniAOu",
	"iDurxrrNHLZT4pbN4KW8Mwuarda1NiuYW8vmRl65WPSZi/0qE7L8QemDEqov1P8bAAD//z69eXKGMwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
