// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for AddMemberRequestRole.
const (
	AddMemberRequestRoleAdmin  AddMemberRequestRole = "admin"
	AddMemberRequestRoleEditor AddMemberRequestRole = "editor"
)

// Defines values for ChangeMemberRoleRequestRole.
const (
	ChangeMemberRoleRequestRoleAdmin  ChangeMemberRoleRequestRole = "admin"
	ChangeMemberRoleRequestRoleEditor ChangeMemberRoleRequestRole = "editor"
)

// Defines values for CreateInviteRequestRole.
const (
	CreateInviteRequestRoleAdmin  CreateInviteRequestRole = "admin"
	CreateInviteRequestRoleEditor CreateInviteRequestRole = "editor"
)

// Defines values for FormInviteRole.
const (
	FormInviteRoleAdmin  FormInviteRole = "admin"
	FormInviteRoleEditor FormInviteRole = "editor"
)

// Defines values for MemberRole.
const (
	Admin  MemberRole = "admin"
	Editor MemberRole = "editor"
)

// Defines values for TicketPriority.
const (
	High   TicketPriority = "high"
	Low    TicketPriority = "low"
	Medium TicketPriority = "medium"
)

// AddMemberRequest defines model for AddMemberRequest.
type AddMemberRequest struct {
	Email openapi_types.Email  `json:"email"`
	Role  AddMemberRequestRole `json:"role"`
}

// AddMemberRequestRole defines model for AddMemberRequest.Role.
type AddMemberRequestRole string

// ChangeMemberRoleRequest defines model for ChangeMemberRoleRequest.
type ChangeMemberRoleRequest struct {
	Role ChangeMemberRoleRequestRole `json:"role"`
}

// ChangeMemberRoleRequestRole defines model for ChangeMemberRoleRequest.Role.
type ChangeMemberRoleRequestRole string

// CreateFormStatusRequest defines model for CreateFormStatusRequest.
type CreateFormStatusRequest struct {
	Color        *string `json:"color"`
	DisplayOrder int     `json:"display_order"`
	IsDefault    *bool   `json:"is_default,omitempty"`
	Name         string  `json:"name"`
}

// CreateInviteRequest defines model for CreateInviteRequest.
type CreateInviteRequest struct {
	Email openapi_types.Email     `json:"email"`
	Role  CreateInviteRequestRole `json:"role"`
}

// CreateInviteRequestRole defines model for CreateInviteRequest.Role.
type CreateInviteRequestRole string

// CreateInviteResponse defines model for CreateInviteResponse.
type CreateInviteResponse struct {
	ExpiresAt time.Time          `json:"expires_at"`
	InviteId  openapi_types.UUID `json:"invite_id"`
}

// Error defines model for Error.
type Error struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details"`
	Message *string                 `json:"message"`
}

// Form defines model for Form.
type Form struct {
	CreatedAt           time.Time          `json:"created_at"`
	Description         *string            `json:"description"`
	EmailCollectionType *string            `json:"email_collection_type"`
	Id                  openapi_types.UUID `json:"id"`
	SyncedAt            *time.Time         `json:"synced_at"`
	Title               string             `json:"title"`
	TitleQuestionId     *string            `json:"title_question_id"`
}

// FormInvite defines model for FormInvite.
type FormInvite struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	ExpiresAt time.Time           `json:"expires_at"`
	Id        openapi_types.UUID  `json:"id"`
	InvitedBy openapi_types.UUID  `json:"invited_by"`
	Role      FormInviteRole      `json:"role"`
}

// FormInviteRole defines model for FormInvite.Role.
type FormInviteRole string

// FormQuestion defines model for FormQuestion.
type FormQuestion struct {
	Options      *[]string `json:"options"`
	QuestionId   string    `json:"question_id"`
	QuestionType string    `json:"question_type"`
	Title        string    `json:"title"`
}

// FormStatus defines model for FormStatus.
type FormStatus struct {
	Color        *string            `json:"color"`
	DisplayOrder int                `json:"display_order"`
	Id           openapi_types.UUID `json:"id"`
	IsDefault    bool               `json:"is_default"`
	Name         string             `json:"name"`
}

// FormSummary defines model for FormSummary.
type FormSummary struct {
	Id       openapi_types.UUID `json:"id"`
	SyncedAt *time.Time         `json:"synced_at"`
	Title    string             `json:"title"`
}

// ListFormInvitesResponse defines model for ListFormInvitesResponse.
type ListFormInvitesResponse struct {
	Invites []FormInvite `json:"invites"`
}

// ListFormQuestionsResponse defines model for ListFormQuestionsResponse.
type ListFormQuestionsResponse struct {
	Questions []FormQuestion `json:"questions"`
}

// ListFormStatusesResponse defines model for ListFormStatusesResponse.
type ListFormStatusesResponse struct {
	Statuses []FormStatus `json:"statuses"`
}

// ListFormsResponse defines model for ListFormsResponse.
type ListFormsResponse struct {
	Forms []FormSummary `json:"forms"`
}

// ListMembersResponse defines model for ListMembersResponse.
type ListMembersResponse struct {
	Members []Member `json:"members"`
}

// ListTicketHistoriesResponse defines model for ListTicketHistoriesResponse.
type ListTicketHistoriesResponse struct {
	Histories []TicketHistory `json:"histories"`
}

// ListTicketsResponse defines model for ListTicketsResponse.
type ListTicketsResponse struct {
	Tickets []TicketSummary `json:"tickets"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	SessionId string `json:"session_id"`
}

// Member defines model for Member.
type Member struct {
	DisplayName *string             `json:"display_name,omitempty"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	Role        MemberRole          `json:"role"`
}

// MemberRole defines model for Member.Role.
type MemberRole string

// PasswordResetConfirmRequest defines model for PasswordResetConfirmRequest.
type PasswordResetConfirmRequest struct {
	NewPassword string `json:"new_password"`
	Token       string `json:"token"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	Email openapi_types.Email `json:"email"`
}

// RegisterFormRequest defines model for RegisterFormRequest.
type RegisterFormRequest struct {
	// Url Google Forms のURLまたはフォームID
	Url string `json:"url"`
}

// RegisterFormResponse defines model for RegisterFormResponse.
type RegisterFormResponse struct {
	Id openapi_types.UUID `json:"id"`
}

// ResendVerificationRequest defines model for ResendVerificationRequest.
type ResendVerificationRequest struct {
	Email openapi_types.Email `json:"email"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// SignupResponse defines model for SignupResponse.
type SignupResponse struct {
	Id openapi_types.UUID `json:"id"`
}

// SyncResponse defines model for SyncResponse.
type SyncResponse struct {
	Last       *time.Time `json:"last"`
	NewTickets int        `json:"new_tickets"`
	Synced     int        `json:"synced"`
}

// TicketAnswer defines model for TicketAnswer.
type TicketAnswer struct {
	DisplayValue  string   `json:"display_value"`
	QuestionId    string   `json:"question_id"`
	QuestionTitle string   `json:"question_title"`
	QuestionType  string   `json:"question_type"`
	Values        []string `json:"values"`
}

// TicketAssignee defines model for TicketAssignee.
type TicketAssignee struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
}

// TicketDetail defines model for TicketDetail.
type TicketDetail struct {
	Answers         []TicketAnswer     `json:"answers"`
	Assignee        *TicketAssignee    `json:"assignee"`
	CreatedAt       time.Time          `json:"created_at"`
	FormId          openapi_types.UUID `json:"form_id"`
	FormTitle       string             `json:"form_title"`
	Id              openapi_types.UUID `json:"id"`
	Priority        TicketPriority     `json:"priority"`
	RespondentEmail *string            `json:"respondent_email"`
	ResponseId      string             `json:"response_id"`
	Status          TicketStatus       `json:"status"`
	SubmittedAt     time.Time          `json:"submitted_at"`
	Title           string             `json:"title"`
	TitleQuestionId *string            `json:"title_question_id"`
}

// TicketHistory defines model for TicketHistory.
type TicketHistory struct {
	ChangedBy     *openapi_types.UUID `json:"changed_by"`
	ChangedByName string              `json:"changed_by_name"`
	CreatedAt     time.Time           `json:"created_at"`
	FieldName     string              `json:"field_name"`
	Id            openapi_types.UUID  `json:"id"`
	NewValue      *string             `json:"new_value"`
	OldValue      *string             `json:"old_value"`
	TicketId      openapi_types.UUID  `json:"ticket_id"`
}

// TicketPriority defines model for TicketPriority.
type TicketPriority string

// TicketStatus defines model for TicketStatus.
type TicketStatus struct {
	Color *string            `json:"color"`
	Id    openapi_types.UUID `json:"id"`
	Name  string             `json:"name"`
}

// TicketSummary defines model for TicketSummary.
type TicketSummary struct {
	Assignee        *TicketAssignee    `json:"assignee"`
	CreatedAt       time.Time          `json:"created_at"`
	FormId          openapi_types.UUID `json:"form_id"`
	FormTitle       string             `json:"form_title"`
	Id              openapi_types.UUID `json:"id"`
	Priority        TicketPriority     `json:"priority"`
	RespondentEmail *string            `json:"respondent_email"`
	ResponseId      string             `json:"response_id"`
	Status          TicketStatus       `json:"status"`
	SubmittedAt     time.Time          `json:"submitted_at"`
	Title           string             `json:"title"`
	TitleQuestionId *string            `json:"title_question_id"`
}

// UpdateFormRequest defines model for UpdateFormRequest.
type UpdateFormRequest struct {
	TitleQuestionId *string `json:"title_question_id"`
}

// UpdateFormStatusRequest defines model for UpdateFormStatusRequest.
type UpdateFormStatusRequest struct {
	Color        *string `json:"color"`
	DisplayOrder *int    `json:"display_order,omitempty"`
	Name         *string `json:"name,omitempty"`
}

// UpdateTicketRequest defines model for UpdateTicketRequest.
type UpdateTicketRequest struct {
	AssigneeId *openapi_types.UUID `json:"assignee_id"`
	Priority   *TicketPriority     `json:"priority,omitempty"`
	StatusId   *openapi_types.UUID `json:"status_id,omitempty"`
}

// UpdateUserProfileRequest defines model for UpdateUserProfileRequest.
type UpdateUserProfileRequest struct {
	DisplayName string `json:"display_name"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	VerifiedAt  *time.Time          `json:"verified_at"`
}

// VerifyEmailRequest defines model for VerifyEmailRequest.
type VerifyEmailRequest struct {
	Token string `json:"token"`
}

// PatchV1MePasswordJSONBody defines parameters for PatchV1MePassword.
type PatchV1MePasswordJSONBody struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// GetV1TicketsParams defines parameters for GetV1Tickets.
type GetV1TicketsParams struct {
	// Form フィルタリング用のフォームID
	Form *openapi_types.UUID `form:"form,omitempty" json:"form,omitempty"`

	// StatusId フィルタリング用のステータスID
	StatusId *openapi_types.UUID `form:"status_id,omitempty" json:"status_id,omitempty"`
}

// PostV1AuthLoginJSONRequestBody defines body for PostV1AuthLogin for application/json ContentType.
type PostV1AuthLoginJSONRequestBody = LoginRequest

// PostV1AuthPasswordResetJSONRequestBody defines body for PostV1AuthPasswordReset for application/json ContentType.
type PostV1AuthPasswordResetJSONRequestBody = PasswordResetRequest

// PostV1AuthPasswordResetConfirmJSONRequestBody defines body for PostV1AuthPasswordResetConfirm for application/json ContentType.
type PostV1AuthPasswordResetConfirmJSONRequestBody = PasswordResetConfirmRequest

// PostV1AuthSignupJSONRequestBody defines body for PostV1AuthSignup for application/json ContentType.
type PostV1AuthSignupJSONRequestBody = SignupRequest

// PostV1AuthVerifyEmailJSONRequestBody defines body for PostV1AuthVerifyEmail for application/json ContentType.
type PostV1AuthVerifyEmailJSONRequestBody = VerifyEmailRequest

// PostV1AuthVerifyEmailResendJSONRequestBody defines body for PostV1AuthVerifyEmailResend for application/json ContentType.
type PostV1AuthVerifyEmailResendJSONRequestBody = ResendVerificationRequest

// PostV1FormsJSONRequestBody defines body for PostV1Forms for application/json ContentType.
type PostV1FormsJSONRequestBody = RegisterFormRequest

// PatchV1FormsIdJSONRequestBody defines body for PatchV1FormsId for application/json ContentType.
type PatchV1FormsIdJSONRequestBody = UpdateFormRequest

// PostV1FormsIdInvitesJSONRequestBody defines body for PostV1FormsIdInvites for application/json ContentType.
type PostV1FormsIdInvitesJSONRequestBody = CreateInviteRequest

// PostV1FormsIdMembersJSONRequestBody defines body for PostV1FormsIdMembers for application/json ContentType.
type PostV1FormsIdMembersJSONRequestBody = AddMemberRequest

// PutV1FormsIdMembersUserIdJSONRequestBody defines body for PutV1FormsIdMembersUserId for application/json ContentType.
type PutV1FormsIdMembersUserIdJSONRequestBody = ChangeMemberRoleRequest

// PostV1FormsIdStatusesJSONRequestBody defines body for PostV1FormsIdStatuses for application/json ContentType.
type PostV1FormsIdStatusesJSONRequestBody = CreateFormStatusRequest

// PatchV1FormsIdStatusesStatusIdJSONRequestBody defines body for PatchV1FormsIdStatusesStatusId for application/json ContentType.
type PatchV1FormsIdStatusesStatusIdJSONRequestBody = UpdateFormStatusRequest

// PatchV1MeJSONRequestBody defines body for PatchV1Me for application/json ContentType.
type PatchV1MeJSONRequestBody = UpdateUserProfileRequest

// PatchV1MePasswordJSONRequestBody defines body for PatchV1MePassword for application/json ContentType.
type PatchV1MePasswordJSONRequestBody PatchV1MePasswordJSONBody

// PatchV1TicketsTicketIdJSONRequestBody defines body for PatchV1TicketsTicketId for application/json ContentType.
type PatchV1TicketsTicketIdJSONRequestBody = UpdateTicketRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ヘルスチェック
	// (GET /healthz)
	GetHealthz(c *gin.Context)
	// ログイン
	// (POST /v1/auth/login)
	PostV1AuthLogin(c *gin.Context)
	// ログアウト
	// (POST /v1/auth/logout)
	PostV1AuthLogout(c *gin.Context)
	// パスワードリセット
	// (POST /v1/auth/password-reset)
	PostV1AuthPasswordReset(c *gin.Context)
	// パスワードリセット
	// (POST /v1/auth/password-reset/confirm)
	PostV1AuthPasswordResetConfirm(c *gin.Context)
	// サインアップ
	// (POST /v1/auth/signup)
	PostV1AuthSignup(c *gin.Context)
	// メール認証
	// (POST /v1/auth/verify-email)
	PostV1AuthVerifyEmail(c *gin.Context)
	// 認証メール再送
	// (POST /v1/auth/verify-email/resend)
	PostV1AuthVerifyEmailResend(c *gin.Context)
	// フォーム一覧
	// (GET /v1/forms)
	GetV1Forms(c *gin.Context)
	// フォーム登録
	// (POST /v1/forms)
	PostV1Forms(c *gin.Context)
	// フォーム取得
	// (GET /v1/forms/{id})
	GetV1FormsId(c *gin.Context, id openapi_types.UUID)
	// フォーム更新
	// (PATCH /v1/forms/{id})
	PatchV1FormsId(c *gin.Context, id openapi_types.UUID)
	// 招待一覧取得
	// (GET /v1/forms/{id}/invites)
	GetV1FormsIdInvites(c *gin.Context, id openapi_types.UUID)
	// 招待作成
	// (POST /v1/forms/{id}/invites)
	PostV1FormsIdInvites(c *gin.Context, id openapi_types.UUID)
	// 招待削除
	// (DELETE /v1/forms/{id}/invites/{invite_id})
	DeleteV1FormsIdInvitesInviteId(c *gin.Context, id openapi_types.UUID, inviteId openapi_types.UUID)
	// メンバー一覧取得
	// (GET /v1/forms/{id}/members)
	GetV1FormsIdMembers(c *gin.Context, id openapi_types.UUID)
	// メンバー追加
	// (POST /v1/forms/{id}/members)
	PostV1FormsIdMembers(c *gin.Context, id openapi_types.UUID)
	// メンバー削除
	// (DELETE /v1/forms/{id}/members/{user_id})
	DeleteV1FormsIdMembersUserId(c *gin.Context, id openapi_types.UUID, userId openapi_types.UUID)
	// メンバーロール変更
	// (PUT /v1/forms/{id}/members/{user_id})
	PutV1FormsIdMembersUserId(c *gin.Context, id openapi_types.UUID, userId openapi_types.UUID)
	// 質問一覧取得
	// (GET /v1/forms/{id}/questions)
	GetV1FormsIdQuestions(c *gin.Context, id openapi_types.UUID)
	// ステータス一覧取得
	// (GET /v1/forms/{id}/statuses)
	GetV1FormsIdStatuses(c *gin.Context, id openapi_types.UUID)
	// ステータス作成
	// (POST /v1/forms/{id}/statuses)
	PostV1FormsIdStatuses(c *gin.Context, id openapi_types.UUID)
	// ステータス削除
	// (DELETE /v1/forms/{id}/statuses/{status_id})
	DeleteV1FormsIdStatusesStatusId(c *gin.Context, id openapi_types.UUID, statusId openapi_types.UUID)
	// ステータス更新
	// (PATCH /v1/forms/{id}/statuses/{status_id})
	PatchV1FormsIdStatusesStatusId(c *gin.Context, id openapi_types.UUID, statusId openapi_types.UUID)
	// デフォルトステータス設定
	// (POST /v1/forms/{id}/statuses/{status_id}/default)
	PostV1FormsIdStatusesStatusIdDefault(c *gin.Context, id openapi_types.UUID, statusId openapi_types.UUID)
	// 回答の同期
	// (POST /v1/forms/{id}/sync)
	PostV1FormsIdSync(c *gin.Context, id openapi_types.UUID)
	// 招待受諾
	// (POST /v1/invites/{invite_id}/accept)
	PostV1InvitesInviteIdAccept(c *gin.Context, inviteId openapi_types.UUID)
	// アカウント削除
	// (DELETE /v1/me)
	DeleteV1Me(c *gin.Context)
	// プロフィール取得
	// (GET /v1/me)
	GetV1Me(c *gin.Context)
	// プロフィール更新
	// (PATCH /v1/me)
	PatchV1Me(c *gin.Context)
	// パスワード変更
	// (PATCH /v1/me/password)
	PatchV1MePassword(c *gin.Context)
	// チケット一覧取得
	// (GET /v1/tickets)
	GetV1Tickets(c *gin.Context, params GetV1TicketsParams)
	// チケット詳細取得
	// (GET /v1/tickets/{ticket_id})
	GetV1TicketsTicketId(c *gin.Context, ticketId openapi_types.UUID)
	// チケット更新
	// (PATCH /v1/tickets/{ticket_id})
	PatchV1TicketsTicketId(c *gin.Context, ticketId openapi_types.UUID)
	// チケット履歴一覧取得
	// (GET /v1/tickets/{ticket_id}/histories)
	GetV1TicketsTicketIdHistories(c *gin.Context, ticketId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthz(c)
}

// PostV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostV1AuthLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1AuthLogin(c)
}

// PostV1AuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostV1AuthLogout(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1AuthLogout(c)
}

// PostV1AuthPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) PostV1AuthPasswordReset(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1AuthPasswordReset(c)
}

// PostV1AuthPasswordResetConfirm operation middleware
func (siw *ServerInterfaceWrapper) PostV1AuthPasswordResetConfirm(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1AuthPasswordResetConfirm(c)
}

// PostV1AuthSignup operation middleware
func (siw *ServerInterfaceWrapper) PostV1AuthSignup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1AuthSignup(c)
}

// PostV1AuthVerifyEmail operation middleware
func (siw *ServerInterfaceWrapper) PostV1AuthVerifyEmail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1AuthVerifyEmail(c)
}

// PostV1AuthVerifyEmailResend operation middleware
func (siw *ServerInterfaceWrapper) PostV1AuthVerifyEmailResend(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1AuthVerifyEmailResend(c)
}

// GetV1Forms operation middleware
func (siw *ServerInterfaceWrapper) GetV1Forms(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Forms(c)
}

// PostV1Forms operation middleware
func (siw *ServerInterfaceWrapper) PostV1Forms(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1Forms(c)
}

// GetV1FormsId operation middleware
func (siw *ServerInterfaceWrapper) GetV1FormsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1FormsId(c, id)
}

// PatchV1FormsId operation middleware
func (siw *ServerInterfaceWrapper) PatchV1FormsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchV1FormsId(c, id)
}

// GetV1FormsIdInvites operation middleware
func (siw *ServerInterfaceWrapper) GetV1FormsIdInvites(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1FormsIdInvites(c, id)
}

// PostV1FormsIdInvites operation middleware
func (siw *ServerInterfaceWrapper) PostV1FormsIdInvites(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1FormsIdInvites(c, id)
}

// DeleteV1FormsIdInvitesInviteId operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1FormsIdInvitesInviteId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "invite_id" -------------
	var inviteId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "invite_id", c.Param("invite_id"), &inviteId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter invite_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteV1FormsIdInvitesInviteId(c, id, inviteId)
}

// GetV1FormsIdMembers operation middleware
func (siw *ServerInterfaceWrapper) GetV1FormsIdMembers(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1FormsIdMembers(c, id)
}

// PostV1FormsIdMembers operation middleware
func (siw *ServerInterfaceWrapper) PostV1FormsIdMembers(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1FormsIdMembers(c, id)
}

// DeleteV1FormsIdMembersUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1FormsIdMembersUserId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "user_id" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteV1FormsIdMembersUserId(c, id, userId)
}

// PutV1FormsIdMembersUserId operation middleware
func (siw *ServerInterfaceWrapper) PutV1FormsIdMembersUserId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "user_id" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutV1FormsIdMembersUserId(c, id, userId)
}

// GetV1FormsIdQuestions operation middleware
func (siw *ServerInterfaceWrapper) GetV1FormsIdQuestions(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1FormsIdQuestions(c, id)
}

// GetV1FormsIdStatuses operation middleware
func (siw *ServerInterfaceWrapper) GetV1FormsIdStatuses(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1FormsIdStatuses(c, id)
}

// PostV1FormsIdStatuses operation middleware
func (siw *ServerInterfaceWrapper) PostV1FormsIdStatuses(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1FormsIdStatuses(c, id)
}

// DeleteV1FormsIdStatusesStatusId operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1FormsIdStatusesStatusId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "status_id" -------------
	var statusId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "status_id", c.Param("status_id"), &statusId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteV1FormsIdStatusesStatusId(c, id, statusId)
}

// PatchV1FormsIdStatusesStatusId operation middleware
func (siw *ServerInterfaceWrapper) PatchV1FormsIdStatusesStatusId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "status_id" -------------
	var statusId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "status_id", c.Param("status_id"), &statusId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchV1FormsIdStatusesStatusId(c, id, statusId)
}

// PostV1FormsIdStatusesStatusIdDefault operation middleware
func (siw *ServerInterfaceWrapper) PostV1FormsIdStatusesStatusIdDefault(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "status_id" -------------
	var statusId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "status_id", c.Param("status_id"), &statusId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1FormsIdStatusesStatusIdDefault(c, id, statusId)
}

// PostV1FormsIdSync operation middleware
func (siw *ServerInterfaceWrapper) PostV1FormsIdSync(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1FormsIdSync(c, id)
}

// PostV1InvitesInviteIdAccept operation middleware
func (siw *ServerInterfaceWrapper) PostV1InvitesInviteIdAccept(c *gin.Context) {

	var err error

	// ------------- Path parameter "invite_id" -------------
	var inviteId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "invite_id", c.Param("invite_id"), &inviteId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter invite_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1InvitesInviteIdAccept(c, inviteId)
}

// DeleteV1Me operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1Me(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteV1Me(c)
}

// GetV1Me operation middleware
func (siw *ServerInterfaceWrapper) GetV1Me(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Me(c)
}

// PatchV1Me operation middleware
func (siw *ServerInterfaceWrapper) PatchV1Me(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchV1Me(c)
}

// PatchV1MePassword operation middleware
func (siw *ServerInterfaceWrapper) PatchV1MePassword(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchV1MePassword(c)
}

// GetV1Tickets operation middleware
func (siw *ServerInterfaceWrapper) GetV1Tickets(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetV1TicketsParams

	// ------------- Optional query parameter "form" -------------

	err = runtime.BindQueryParameter("form", true, false, "form", c.Request.URL.Query(), &params.Form)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter form: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "status_id", c.Request.URL.Query(), &params.StatusId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Tickets(c, params)
}

// GetV1TicketsTicketId operation middleware
func (siw *ServerInterfaceWrapper) GetV1TicketsTicketId(c *gin.Context) {

	var err error

	// ------------- Path parameter "ticket_id" -------------
	var ticketId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "ticket_id", c.Param("ticket_id"), &ticketId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ticket_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1TicketsTicketId(c, ticketId)
}

// PatchV1TicketsTicketId operation middleware
func (siw *ServerInterfaceWrapper) PatchV1TicketsTicketId(c *gin.Context) {

	var err error

	// ------------- Path parameter "ticket_id" -------------
	var ticketId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "ticket_id", c.Param("ticket_id"), &ticketId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ticket_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchV1TicketsTicketId(c, ticketId)
}

// GetV1TicketsTicketIdHistories operation middleware
func (siw *ServerInterfaceWrapper) GetV1TicketsTicketIdHistories(c *gin.Context) {

	var err error

	// ------------- Path parameter "ticket_id" -------------
	var ticketId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "ticket_id", c.Param("ticket_id"), &ticketId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ticket_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1TicketsTicketIdHistories(c, ticketId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz)
	router.POST(options.BaseURL+"/v1/auth/login", wrapper.PostV1AuthLogin)
	router.POST(options.BaseURL+"/v1/auth/logout", wrapper.PostV1AuthLogout)
	router.POST(options.BaseURL+"/v1/auth/password-reset", wrapper.PostV1AuthPasswordReset)
	router.POST(options.BaseURL+"/v1/auth/password-reset/confirm", wrapper.PostV1AuthPasswordResetConfirm)
	router.POST(options.BaseURL+"/v1/auth/signup", wrapper.PostV1AuthSignup)
	router.POST(options.BaseURL+"/v1/auth/verify-email", wrapper.PostV1AuthVerifyEmail)
	router.POST(options.BaseURL+"/v1/auth/verify-email/resend", wrapper.PostV1AuthVerifyEmailResend)
	router.GET(options.BaseURL+"/v1/forms", wrapper.GetV1Forms)
	router.POST(options.BaseURL+"/v1/forms", wrapper.PostV1Forms)
	router.GET(options.BaseURL+"/v1/forms/:id", wrapper.GetV1FormsId)
	router.PATCH(options.BaseURL+"/v1/forms/:id", wrapper.PatchV1FormsId)
	router.GET(options.BaseURL+"/v1/forms/:id/invites", wrapper.GetV1FormsIdInvites)
	router.POST(options.BaseURL+"/v1/forms/:id/invites", wrapper.PostV1FormsIdInvites)
	router.DELETE(options.BaseURL+"/v1/forms/:id/invites/:invite_id", wrapper.DeleteV1FormsIdInvitesInviteId)
	router.GET(options.BaseURL+"/v1/forms/:id/members", wrapper.GetV1FormsIdMembers)
	router.POST(options.BaseURL+"/v1/forms/:id/members", wrapper.PostV1FormsIdMembers)
	router.DELETE(options.BaseURL+"/v1/forms/:id/members/:user_id", wrapper.DeleteV1FormsIdMembersUserId)
	router.PUT(options.BaseURL+"/v1/forms/:id/members/:user_id", wrapper.PutV1FormsIdMembersUserId)
	router.GET(options.BaseURL+"/v1/forms/:id/questions", wrapper.GetV1FormsIdQuestions)
	router.GET(options.BaseURL+"/v1/forms/:id/statuses", wrapper.GetV1FormsIdStatuses)
	router.POST(options.BaseURL+"/v1/forms/:id/statuses", wrapper.PostV1FormsIdStatuses)
	router.DELETE(options.BaseURL+"/v1/forms/:id/statuses/:status_id", wrapper.DeleteV1FormsIdStatusesStatusId)
	router.PATCH(options.BaseURL+"/v1/forms/:id/statuses/:status_id", wrapper.PatchV1FormsIdStatusesStatusId)
	router.POST(options.BaseURL+"/v1/forms/:id/statuses/:status_id/default", wrapper.PostV1FormsIdStatusesStatusIdDefault)
	router.POST(options.BaseURL+"/v1/forms/:id/sync", wrapper.PostV1FormsIdSync)
	router.POST(options.BaseURL+"/v1/invites/:invite_id/accept", wrapper.PostV1InvitesInviteIdAccept)
	router.DELETE(options.BaseURL+"/v1/me", wrapper.DeleteV1Me)
	router.GET(options.BaseURL+"/v1/me", wrapper.GetV1Me)
	router.PATCH(options.BaseURL+"/v1/me", wrapper.PatchV1Me)
	router.PATCH(options.BaseURL+"/v1/me/password", wrapper.PatchV1MePassword)
	router.GET(options.BaseURL+"/v1/tickets", wrapper.GetV1Tickets)
	router.GET(options.BaseURL+"/v1/tickets/:ticket_id", wrapper.GetV1TicketsTicketId)
	router.PATCH(options.BaseURL+"/v1/tickets/:ticket_id", wrapper.PatchV1TicketsTicketId)
	router.GET(options.BaseURL+"/v1/tickets/:ticket_id/histories", wrapper.GetV1TicketsTicketIdHistories)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdW28bx/X/KsT+/4+MV0pSIOWba6eJkJtqx34xBGLFHZET7+5sZmZlM4KAiERdO3Vg",
	"F4jjpg6aNHUTx4IvqV2gbhznw2woy9+imJnd5V5m9iKRS7rmkwhyLmfm/M7vnDlz0ZbWQbaLHOBQorW2",
	"NNLpAdvgH4+a5jvAXgf4BPjQA4Sy71yMXIApBLwEsA1osQ8bCNsG1VrBN02N9l2gtTRCMXS62nZTw8gC",
	"vIrj2VrrjGaYNnS0pgZMSBHW1jJVWB3woQcxMFn5sGHezrg0Wv8AdCjr4FjPcLogEBhZQCn0YSVRS4CB",
	"QcFvEbZPUoN6RClBB1kIsw+OZ1nGOhOHYg9IZs2ExLWMfhthE/AaQQnoUNAFmBWBpG2CDcOzaOz3dYQs",
	"YDjsd8ewQewXxaB4qXR/6kGuOJuQgucDFwmBiYscAiQSn3chBqRt0ITYpkHBSxTyucmIDnmbbWgmqnge",
	"NLUiqcdVm/GuZfK/jrEASxpDpkytTc0E1IAWL2OYJqQQOYa1GqsroKaA3rhfGxBidEEJmKbGxiWTjYRZ",
	"hmQgXD9mpZk3Aelg6LKxlTIjDpJ2B1kW6LBKbVGiRM1Sym1qpO908sdQ2BOF1JJrlP/S5qbGZBciVdOJ",
	"kJr30IzPuEpNwlwmo6wKZHAgKyynIWFxZnu9X6r4YWlJWHacmxIiJIZaSiO/C9Sf1QnidsA/QgpsIsWQ",
	"Ai4Gxkaf/Z5CV6Z+9HtoOaXxm5qYeEdjSCabV82BcKvT9qcl8TQRt8vblvreRA/KCfFs28D97IzMnrbU",
	"BCQbzNuQ0DHvELWfFjaUBPv/Y7ChtbT/08eRrB6EsXqMzLbTqJf6ZJIrX2iFORKGUK4mY2TeRVKOm8+T",
	"U1hK3kSSoEQlKQMDLJIxajtPxBzZGBIrChYYQpFkomWVWGLxkCOYLQqUFk00WChV2KxKrvdh5yygb0JC",
	"EYZ5Su2FRUpLGG+6ePrG7eeLmiMiFQUqClhWv2HrUvFQFzqTWLK4BiHnEDaLWS9sIqqRI5fSUAEhSsec",
	"NrxxWVlPARwzXYSeR+GzKoVwJT3P5OMr2YBXg3k/AQigx5CzAbGtRIADzrXjqrWh8zZwurSntV6TOT50",
	"FjjFKhHFmsnWC2U9PEylSJT1ewJ0IaEAMxpVduth3mli3aW9gVDXAg1O5g1/5+6pE2/7O0/8na/8nXv+",
	"8Jo/+N4fPvaHX68cLxSPtV8snDIoOMgK3FR0SIBjngYYbsCOwQZaoypOwq7jucoOJ2mmpYFexGjNpFh5",
	"w6pBfSf7TkfdkWWQQ0S6zIJj3iu7chDRtOy3NE2LgskmZcMRzu+oQ87l0famYXkgf9VWuKpTJh+KF368",
	"+4LlZ6mQViwJUzKlJYj6a6bGnzN/hMCuA8AcOD6ZF0sI0cyhBzGa4zy/x9N7lvXehtY6Uy2ASs+BwdFV",
	"NSALMFmk2rDx7HDWogGFwWd2Wc8z+qqUTaG9jqur9XuQfNYGBJapbrJkAMRMPzLcwrEgy6xQWlBK+8CI",
	"HNfPzmJi/IWZK6HhVQwRhrQfD/h6sNvTmpoNTOjZWlOz0DlJ1Be2cPjMT1m1VEzbqAetzM0YMTqqYsIR",
	"jW2vpdF/UCQjbLdLTgwvq3YTJVtxY0goHnGEGz79zKubwKHtiJQLlY6DUEDl/0gEqxIMGuU+iLduQ1p1",
	"sqef3w/VmVBWchKiIcdUMc7CJgZWaNunXDPY7lRGrAccWU5Xde6sqrlAIaAAilK40PAVJlco8sGNRyi9",
	"tENQDO8UAXgVow2Ys7leEFGlYFu4dIh1ORdpi02+MDxUyjwvkVE4H3xh2n+dFVcbXZXERLYTBhfQ8Rh0",
	"TjJAhYaFzkJw1GOLxC0NsuW/+Cp0hC0xGe0w3xGGhS58C7C4kG/BbaBsFuHo6krDRB3PBg7lC+7GBsIN",
	"2hOJBaNxdHUloqiWFv9uE2Ai2lg6snxkicdJLnAMF2ot7ZUjS0de4QtV2uMj0HvAsGjvI/a5C6jYOQOY",
	"d7liai3tDUDfDIqMSZNXfXlpScyBQ4Ej9nvAeaq7lgGd8ZkZcYzAsF0uKDorMa301rX23luJCddaZ9YY",
	"DQeRg+YP/+wPd/3BI3+44w++84dDf3CP19A3l3XDoz3dQl0hhIuIZFCriNDTy0xvPM2oCQwAQn+DzH5q",
	"UIbrWkHSQ/+AoNTQ8hgnkVrdTiItiE8KJvTQfQdrfsUcN7VXJ9ilOJIh6eq0YUFTgBiIMqzj5el3vOJs",
	"sq4bHQxYiAQNi4i+X5l+35yNGg6ijZAdWde/qmO+VxwKsGNYDQLwJsDhpOda1B1/cN8f3PSHDzKGhDxa",
	"0pJYyQymX82S27uocSyYgbqgcMphw0EYfsQUsS0b/Df+4Ft/eDE5/jCj9xIGBJSah0TGekrMIs2Kl2KY",
	"lyWuptMBLhX4nBEf5ELzT5zp7/Gs+SV/eNsf/MgoP19Tekfsa1TWWLAfUofiUlsvpfRXwppmxuivTr/j",
	"91kcxVl1A3mO2UC4IY4MmZMBEeFJ+TKgEen7KcEkueVRChjLE+9cHTuIw6PmjOH267qcuGFhYJj9BjgP",
	"CSXz7MYH/xI+nDkzhu7rSXTzSKT/UrQALMJ4bF01JaBLVm4LGpwiDf6NE+Du/u1P9289VoNDx3zDtyJG",
	"xC7xlJCi3oL+34x7hIoijY0ufPrs451IY9FZMNWa/fQyP4CgTXOJmTmylrPMnHWIPz538cu/P97/9jue",
	"OcyB9nj2pgHl7NmSmn289ATJ3Hr62sFTE42LM0IRjeeA9ukXPz67/M+k+etb0NwuwQEr5jRZgF9fmSfD",
	"r0l375bQ2ujK56Mn18XBImzYgPITBWeCTLFr0N44TwxDxzkmgGZMxqLtiTWe0+30JHzGvk5CYfKUlt31",
	"OmgYJ1paMM7sULt34+He5/clXKPHrhkUck5wZ6GOACR9PWLBRpFe9/54Y/Tk9yLkqZmNioKrJEQmT0my",
	"K7k1R1nSS7aLKGu+bOOnL/cuXs1hO30rupa8LdyVBcQl0CS0j/Pv0+AWf2Qh2Dzui8yFRkaXPnn2xc1a",
	"eKopbzR2Df0QHJhFVOyiVKH/DG5dTdt/pi93LXxnMlv2wB9e9YeP59SDxkEyeQ+aeemkvPtc+Lf5wu/+",
	"zz+NPvla5uUCTtK3PAJwRR8XwO8UAfiAHm4BhhmAYeYONoDaoQnSk/GjR3PwOYVlhuKBpUX+43k1D394",
	"J9hzuXlp78ZDGWkmXjMoDOWi5xHqSIZk32JYhHTjTbUHt0fXrtQfzGURFH9oohBA4bsVdeAn80bGAj6x",
	"8xWP/OEFRg6Dn/3BozldFCTQMq28WvbWSc25tfjDK4uM2nzahzK1FrKfvhXdwamy7ggRLv4ukmsq5dR0",
	"Sk6ooQGdhsf9RQ4kZr70GN/5qmO3VQrUae6+HoCSl2qi5Bfhwsk8s7F6W1fGxnrsGb/n3lTLx0yhoR4P",
	"Rj9za3nxFuJ/CM8i7PrDiykM79+6M7r7FymG+06n6LhqqGtWtJ5ofWrgSbzoI5ne0dXLe19+Nbp7+Zf/",
	"XHgxgTS68dendz7zd+6KqYgwI9nV1Q1+Ergk1U1mczCflVKbx+Kk8iLKLb+FfOX6/u6TSOfiInzR4uId",
	"8DxeXhx84w92+c3FB/7w4ji+VieVZOOcHDPF3yaY4/Pg13mW95o/+HuQ641lcfIC+2DyphXDSx6TqDmI",
	"L6m/FyeKLwBOKqy2gR5/RLAITKvjBwMPCqrUUy8exsCh7ZzXWJvV3vRM/x+DdAeFj3g+7/e5ZuJCa3ih",
	"4JjQZCNUXQM6HYRx9NyJ6vZsalss9vij2ucEDyBnw+6kSKFh7bJwf3ib32S8//SzW/7O3czTqTw2+9AD",
	"uJ98bEWruPIsL0FyLaIUIr5unY/VguwJ6sWaM4bvHX/wg7gOntzTSUJc34qeANwuBXfxZ7r3bxLPXy6U",
	"KlXq/vcPnj68X2WjLv7W4xTTxDKcTCu0TD7DVnNUWRali+TwDMwjFcJK2E5P/AuF0rwX/W8GrRbnlv1X",
	"EAs+lCp89MM/9u48rH58YUKsmLr2nnxG78wao03x5IUQhL+yr/UodVu6bqGOYfUQoa3Xll5b0rbXtv8b",
	"AAD//5EW3LWrcQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
