// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: forms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createForm = `-- name: CreateForm :one
INSERT INTO forms (id, form_id, title, description, title_question_id, email_collection_type, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, form_id, title, description, title_question_id, email_collection_type, synced_at, created_at
`

type CreateFormParams struct {
	ID                  pgtype.UUID        `json:"id"`
	FormID              string             `json:"form_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	TitleQuestionID     pgtype.Text        `json:"title_question_id"`
	EmailCollectionType pgtype.Text        `json:"email_collection_type"`
	SyncedAt            pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) (Form, error) {
	row := q.db.QueryRow(ctx, createForm,
		arg.ID,
		arg.FormID,
		arg.Title,
		arg.Description,
		arg.TitleQuestionID,
		arg.EmailCollectionType,
		arg.SyncedAt,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Title,
		&i.Description,
		&i.TitleQuestionID,
		&i.EmailCollectionType,
		&i.SyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteForm = `-- name: DeleteForm :execrows
DELETE FROM forms
WHERE id = $1
`

func (q *Queries) DeleteForm(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteForm, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFormByID = `-- name: GetFormByID :one
SELECT id, form_id, title, description, title_question_id, email_collection_type, synced_at, created_at
FROM forms
WHERE id = $1
`

func (q *Queries) GetFormByID(ctx context.Context, id pgtype.UUID) (Form, error) {
	row := q.db.QueryRow(ctx, getFormByID, id)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Title,
		&i.Description,
		&i.TitleQuestionID,
		&i.EmailCollectionType,
		&i.SyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listForms = `-- name: ListForms :many
SELECT id, form_id, title, description, title_question_id, email_collection_type, synced_at, created_at
FROM forms
ORDER BY created_at DESC
`

func (q *Queries) ListForms(ctx context.Context) ([]Form, error) {
	rows, err := q.db.Query(ctx, listForms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Form
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Title,
			&i.Description,
			&i.TitleQuestionID,
			&i.EmailCollectionType,
			&i.SyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFormSyncedAt = `-- name: UpdateFormSyncedAt :execrows
UPDATE forms
SET synced_at = $2
WHERE id = $1
`

type UpdateFormSyncedAtParams struct {
	ID       pgtype.UUID        `json:"id"`
	SyncedAt pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) UpdateFormSyncedAt(ctx context.Context, arg UpdateFormSyncedAtParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFormSyncedAt, arg.ID, arg.SyncedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFormTitleQuestion = `-- name: UpdateFormTitleQuestion :execrows
UPDATE forms
SET title_question_id = $2
WHERE id = $1
`

type UpdateFormTitleQuestionParams struct {
	ID              pgtype.UUID `json:"id"`
	TitleQuestionID pgtype.Text `json:"title_question_id"`
}

func (q *Queries) UpdateFormTitleQuestion(ctx context.Context, arg UpdateFormTitleQuestionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFormTitleQuestion, arg.ID, arg.TitleQuestionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
