// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFormInvite = `-- name: AcceptFormInvite :one
UPDATE form_invites
SET accepted_at = NOW()
WHERE id = $1
  AND accepted_at IS NULL
RETURNING id, form_id, email, role, invited_by, accepted_at, expires_at, created_at
`

func (q *Queries) AcceptFormInvite(ctx context.Context, id pgtype.UUID) (FormInvite, error) {
	row := q.db.QueryRow(ctx, acceptFormInvite, id)
	var i FormInvite
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createFormInvite = `-- name: CreateFormInvite :one
INSERT INTO form_invites (id, form_id, email, role, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, form_id, email, role, invited_by, accepted_at, expires_at, created_at
`

type CreateFormInviteParams struct {
	ID        pgtype.UUID        `json:"id"`
	FormID    pgtype.UUID        `json:"form_id"`
	Email     string             `json:"email"`
	Role      FormRole           `json:"role"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateFormInvite(ctx context.Context, arg CreateFormInviteParams) (FormInvite, error) {
	row := q.db.QueryRow(ctx, createFormInvite,
		arg.ID,
		arg.FormID,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i FormInvite
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFormInvite = `-- name: DeleteFormInvite :execrows
DELETE FROM form_invites
WHERE id = $1
`

func (q *Queries) DeleteFormInvite(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFormInvite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFormInviteByEmail = `-- name: GetFormInviteByEmail :one
SELECT id, form_id, email, role, invited_by, accepted_at, expires_at, created_at
FROM form_invites
WHERE form_id = $1
  AND email = $2
  AND accepted_at IS NULL
`

type GetFormInviteByEmailParams struct {
	FormID pgtype.UUID `json:"form_id"`
	Email  string      `json:"email"`
}

func (q *Queries) GetFormInviteByEmail(ctx context.Context, arg GetFormInviteByEmailParams) (FormInvite, error) {
	row := q.db.QueryRow(ctx, getFormInviteByEmail, arg.FormID, arg.Email)
	var i FormInvite
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFormInviteForUpdate = `-- name: GetFormInviteForUpdate :one
SELECT id, form_id, email, role, invited_by, accepted_at, expires_at, created_at
FROM form_invites
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetFormInviteForUpdate(ctx context.Context, id pgtype.UUID) (FormInvite, error) {
	row := q.db.QueryRow(ctx, getFormInviteForUpdate, id)
	var i FormInvite
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveFormInvites = `-- name: ListActiveFormInvites :many
SELECT id, form_id, email, role, invited_by, accepted_at, expires_at, created_at
FROM form_invites
WHERE form_id = $1
  AND accepted_at IS NULL
  AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListActiveFormInvites(ctx context.Context, formID pgtype.UUID) ([]FormInvite, error) {
	rows, err := q.db.Query(ctx, listActiveFormInvites, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormInvite
	for rows.Next() {
		var i FormInvite
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.AcceptedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
