// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type FormRole string

const (
	FormRoleAdmin  FormRole = "admin"
	FormRoleEditor FormRole = "editor"
)

func (e *FormRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FormRole(s)
	case string:
		*e = FormRole(s)
	default:
		return fmt.Errorf("unsupported scan type for FormRole: %T", src)
	}
	return nil
}

type NullFormRole struct {
	FormRole FormRole `json:"form_role"`
	Valid    bool     `json:"valid"` // Valid is true if FormRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFormRole) Scan(value interface{}) error {
	if value == nil {
		ns.FormRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FormRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFormRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FormRole), nil
}

type NotificationMode string

const (
	NotificationModeAlways  NotificationMode = "always"
	NotificationModeConfirm NotificationMode = "confirm"
	NotificationModeOff     NotificationMode = "off"
)

func (e *NotificationMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationMode(s)
	case string:
		*e = NotificationMode(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationMode: %T", src)
	}
	return nil
}

type NullNotificationMode struct {
	NotificationMode NotificationMode `json:"notification_mode"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationMode) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationMode), nil
}

type NotificationType string

const (
	NotificationTypeStatusChange     NotificationType = "status_change"
	NotificationTypeAssigneeAssigned NotificationType = "assignee_assigned"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type TicketPriority string

const (
	TicketPriorityHigh   TicketPriority = "high"
	TicketPriorityMedium TicketPriority = "medium"
	TicketPriorityLow    TicketPriority = "low"
)

func (e *TicketPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketPriority(s)
	case string:
		*e = TicketPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketPriority: %T", src)
	}
	return nil
}

type NullTicketPriority struct {
	TicketPriority TicketPriority `json:"ticket_priority"`
	Valid          bool           `json:"valid"` // Valid is true if TicketPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TicketPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketPriority), nil
}

type EmailVerificationToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Form struct {
	ID                  pgtype.UUID        `json:"id"`
	FormID              string             `json:"form_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	TitleQuestionID     pgtype.Text        `json:"title_question_id"`
	EmailCollectionType pgtype.Text        `json:"email_collection_type"`
	SyncedAt            pgtype.Timestamptz `json:"synced_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type FormInvite struct {
	ID         pgtype.UUID        `json:"id"`
	FormID     pgtype.UUID        `json:"form_id"`
	Email      string             `json:"email"`
	Role       FormRole           `json:"role"`
	InvitedBy  pgtype.UUID        `json:"invited_by"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type FormMember struct {
	UserID    pgtype.UUID        `json:"user_id"`
	FormID    pgtype.UUID        `json:"form_id"`
	Role      FormRole           `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type FormNotificationSetting struct {
	FormID           pgtype.UUID        `json:"form_id"`
	NotificationType NotificationType   `json:"notification_type"`
	Mode             NotificationMode   `json:"mode"`
	IncludeDetail    bool               `json:"include_detail"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type FormQuestion struct {
	FormID       pgtype.UUID        `json:"form_id"`
	QuestionID   string             `json:"question_id"`
	Title        string             `json:"title"`
	QuestionType string             `json:"question_type"`
	Options      []byte             `json:"options"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type FormStatus struct {
	ID           pgtype.UUID        `json:"id"`
	FormID       pgtype.UUID        `json:"form_id"`
	Name         string             `json:"name"`
	Color        pgtype.Text        `json:"color"`
	DisplayOrder int32              `json:"display_order"`
	IsDefault    bool               `json:"is_default"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PasswordResetToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Ticket struct {
	ID              pgtype.UUID        `json:"id"`
	FormID          pgtype.UUID        `json:"form_id"`
	ResponseID      string             `json:"response_id"`
	RespondentEmail pgtype.Text        `json:"respondent_email"`
	Answers         []byte             `json:"answers"`
	StatusID        pgtype.UUID        `json:"status_id"`
	AssigneeID      pgtype.UUID        `json:"assignee_id"`
	Priority        string             `json:"priority"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type TicketHistory struct {
	ID            pgtype.UUID        `json:"id"`
	TicketID      pgtype.UUID        `json:"ticket_id"`
	ChangedBy     pgtype.UUID        `json:"changed_by"`
	ChangedByName string             `json:"changed_by_name"`
	FieldName     string             `json:"field_name"`
	OldValue      pgtype.Text        `json:"old_value"`
	NewValue      pgtype.Text        `json:"new_value"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type TicketNotification struct {
	ID               pgtype.UUID        `json:"id"`
	TicketID         pgtype.UUID        `json:"ticket_id"`
	NotificationType NotificationType   `json:"notification_type"`
	SentBy           pgtype.UUID        `json:"sent_by"`
	SentAt           pgtype.Timestamptz `json:"sent_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	VerifiedAt   pgtype.Timestamptz `json:"verified_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
