// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicketNotification = `-- name: CreateTicketNotification :one
INSERT INTO ticket_notifications (id, ticket_id, notification_type, sent_by, sent_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ticket_id, notification_type, sent_by, sent_at
`

type CreateTicketNotificationParams struct {
	ID               pgtype.UUID        `json:"id"`
	TicketID         pgtype.UUID        `json:"ticket_id"`
	NotificationType NotificationType   `json:"notification_type"`
	SentBy           pgtype.UUID        `json:"sent_by"`
	SentAt           pgtype.Timestamptz `json:"sent_at"`
}

func (q *Queries) CreateTicketNotification(ctx context.Context, arg CreateTicketNotificationParams) (TicketNotification, error) {
	row := q.db.QueryRow(ctx, createTicketNotification,
		arg.ID,
		arg.TicketID,
		arg.NotificationType,
		arg.SentBy,
		arg.SentAt,
	)
	var i TicketNotification
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.NotificationType,
		&i.SentBy,
		&i.SentAt,
	)
	return i, err
}

const getFormNotificationSetting = `-- name: GetFormNotificationSetting :one
SELECT form_id, notification_type, mode, include_detail, updated_at
FROM form_notification_settings
WHERE form_id = $1
  AND notification_type = $2
`

type GetFormNotificationSettingParams struct {
	FormID           pgtype.UUID      `json:"form_id"`
	NotificationType NotificationType `json:"notification_type"`
}

func (q *Queries) GetFormNotificationSetting(ctx context.Context, arg GetFormNotificationSettingParams) (FormNotificationSetting, error) {
	row := q.db.QueryRow(ctx, getFormNotificationSetting, arg.FormID, arg.NotificationType)
	var i FormNotificationSetting
	err := row.Scan(
		&i.FormID,
		&i.NotificationType,
		&i.Mode,
		&i.IncludeDetail,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestTicketNotification = `-- name: GetLatestTicketNotification :one
SELECT id, ticket_id, notification_type, sent_by, sent_at
FROM ticket_notifications
WHERE ticket_id = $1
  AND notification_type = $2
ORDER BY sent_at DESC
LIMIT 1
`

type GetLatestTicketNotificationParams struct {
	TicketID         pgtype.UUID      `json:"ticket_id"`
	NotificationType NotificationType `json:"notification_type"`
}

func (q *Queries) GetLatestTicketNotification(ctx context.Context, arg GetLatestTicketNotificationParams) (TicketNotification, error) {
	row := q.db.QueryRow(ctx, getLatestTicketNotification, arg.TicketID, arg.NotificationType)
	var i TicketNotification
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.NotificationType,
		&i.SentBy,
		&i.SentAt,
	)
	return i, err
}

const listFormNotificationSettings = `-- name: ListFormNotificationSettings :many
SELECT form_id, notification_type, mode, include_detail, updated_at
FROM form_notification_settings
WHERE form_id = $1
`

func (q *Queries) ListFormNotificationSettings(ctx context.Context, formID pgtype.UUID) ([]FormNotificationSetting, error) {
	rows, err := q.db.Query(ctx, listFormNotificationSettings, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormNotificationSetting
	for rows.Next() {
		var i FormNotificationSetting
		if err := rows.Scan(
			&i.FormID,
			&i.NotificationType,
			&i.Mode,
			&i.IncludeDetail,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestTicketNotifications = `-- name: ListLatestTicketNotifications :many
SELECT DISTINCT ON (notification_type)
       id, ticket_id, notification_type, sent_by, sent_at
FROM ticket_notifications
WHERE ticket_id = $1
ORDER BY notification_type, sent_at DESC
`

func (q *Queries) ListLatestTicketNotifications(ctx context.Context, ticketID pgtype.UUID) ([]TicketNotification, error) {
	rows, err := q.db.Query(ctx, listLatestTicketNotifications, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketNotification
	for rows.Next() {
		var i TicketNotification
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.NotificationType,
			&i.SentBy,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFormNotificationSetting = `-- name: UpsertFormNotificationSetting :one
INSERT INTO form_notification_settings (form_id, notification_type, mode, include_detail)
VALUES ($1, $2, $3, $4)
ON CONFLICT (form_id, notification_type)
DO UPDATE SET mode = EXCLUDED.mode,
              include_detail = EXCLUDED.include_detail,
              updated_at = NOW()
RETURNING form_id, notification_type, mode, include_detail, updated_at
`

type UpsertFormNotificationSettingParams struct {
	FormID           pgtype.UUID      `json:"form_id"`
	NotificationType NotificationType `json:"notification_type"`
	Mode             NotificationMode `json:"mode"`
	IncludeDetail    bool             `json:"include_detail"`
}

func (q *Queries) UpsertFormNotificationSetting(ctx context.Context, arg UpsertFormNotificationSettingParams) (FormNotificationSetting, error) {
	row := q.db.QueryRow(ctx, upsertFormNotificationSetting,
		arg.FormID,
		arg.NotificationType,
		arg.Mode,
		arg.IncludeDetail,
	)
	var i FormNotificationSetting
	err := row.Scan(
		&i.FormID,
		&i.NotificationType,
		&i.Mode,
		&i.IncludeDetail,
		&i.UpdatedAt,
	)
	return i, err
}
