// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFormAdmins = `-- name: CountFormAdmins :one
SELECT COUNT(*)
FROM form_members
WHERE form_id = $1
  AND role = 'admin'
`

func (q *Queries) CountFormAdmins(ctx context.Context, formID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFormAdmins, formID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFormMember = `-- name: DeleteFormMember :exec
DELETE FROM form_members
WHERE user_id = $1
  AND form_id = $2
`

type DeleteFormMemberParams struct {
	UserID pgtype.UUID `json:"user_id"`
	FormID pgtype.UUID `json:"form_id"`
}

func (q *Queries) DeleteFormMember(ctx context.Context, arg DeleteFormMemberParams) error {
	_, err := q.db.Exec(ctx, deleteFormMember, arg.UserID, arg.FormID)
	return err
}

const getFormMemberRole = `-- name: GetFormMemberRole :one
SELECT role
FROM form_members
WHERE user_id = $1
  AND form_id = $2
`

type GetFormMemberRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	FormID pgtype.UUID `json:"form_id"`
}

func (q *Queries) GetFormMemberRole(ctx context.Context, arg GetFormMemberRoleParams) (FormRole, error) {
	row := q.db.QueryRow(ctx, getFormMemberRole, arg.UserID, arg.FormID)
	var role FormRole
	err := row.Scan(&role)
	return role, err
}

const listFormMembers = `-- name: ListFormMembers :many
SELECT u.id, u.email, u.display_name, u.created_at, m.role
FROM form_members m
JOIN users u ON u.id = m.user_id
WHERE m.form_id = $1
ORDER BY u.email
`

type ListFormMembersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Role        FormRole           `json:"role"`
}

func (q *Queries) ListFormMembers(ctx context.Context, formID pgtype.UUID) ([]ListFormMembersRow, error) {
	rows, err := q.db.Query(ctx, listFormMembers, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormMembersRow
	for rows.Next() {
		var i ListFormMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAccessibleForms = `-- name: ListUserAccessibleForms :many
SELECT f.id, f.form_id, f.title, f.synced_at
FROM form_members m
JOIN forms f ON f.id = m.form_id
WHERE m.user_id = $1
ORDER BY f.title
`

type ListUserAccessibleFormsRow struct {
	ID       pgtype.UUID        `json:"id"`
	FormID   string             `json:"form_id"`
	Title    string             `json:"title"`
	SyncedAt pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) ListUserAccessibleForms(ctx context.Context, userID pgtype.UUID) ([]ListUserAccessibleFormsRow, error) {
	rows, err := q.db.Query(ctx, listUserAccessibleForms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserAccessibleFormsRow
	for rows.Next() {
		var i ListUserAccessibleFormsRow
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Title,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFormMember = `-- name: UpsertFormMember :exec
INSERT INTO form_members (user_id, form_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, form_id) DO UPDATE
SET role = EXCLUDED.role
`

type UpsertFormMemberParams struct {
	UserID pgtype.UUID `json:"user_id"`
	FormID pgtype.UUID `json:"form_id"`
	Role   FormRole    `json:"role"`
}

func (q *Queries) UpsertFormMember(ctx context.Context, arg UpsertFormMemberParams) error {
	_, err := q.db.Exec(ctx, upsertFormMember, arg.UserID, arg.FormID, arg.Role)
	return err
}
