// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTicketsByStatus = `-- name: CountTicketsByStatus :one
SELECT COUNT(1)
FROM tickets
WHERE status_id = $1
`

func (q *Queries) CountTicketsByStatus(ctx context.Context, statusID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTicketsByStatus, statusID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTicket = `-- name: CreateTicket :execrows
INSERT INTO tickets (id, form_id, response_id, respondent_email, answers, status_id, assignee_id, priority, submitted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (form_id, response_id) DO NOTHING
`

type CreateTicketParams struct {
	ID              pgtype.UUID        `json:"id"`
	FormID          pgtype.UUID        `json:"form_id"`
	ResponseID      string             `json:"response_id"`
	RespondentEmail pgtype.Text        `json:"respondent_email"`
	Answers         []byte             `json:"answers"`
	StatusID        pgtype.UUID        `json:"status_id"`
	AssigneeID      pgtype.UUID        `json:"assignee_id"`
	Priority        string             `json:"priority"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (int64, error) {
	result, err := q.db.Exec(ctx, createTicket,
		arg.ID,
		arg.FormID,
		arg.ResponseID,
		arg.RespondentEmail,
		arg.Answers,
		arg.StatusID,
		arg.AssigneeID,
		arg.Priority,
		arg.SubmittedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTicket = `-- name: GetTicket :one
SELECT id, form_id, response_id, respondent_email, answers,
       status_id, assignee_id, priority, submitted_at, created_at
FROM tickets
WHERE id = $1
`

func (q *Queries) GetTicket(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ResponseID,
		&i.RespondentEmail,
		&i.Answers,
		&i.StatusID,
		&i.AssigneeID,
		&i.Priority,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTickets = `-- name: ListTickets :many
SELECT id, form_id, response_id, respondent_email, answers,
       status_id, assignee_id, priority, submitted_at, created_at
FROM tickets
WHERE form_id = $1
  AND ($2::uuid IS NULL OR status_id = $2)
ORDER BY created_at DESC
LIMIT 200
`

type ListTicketsParams struct {
	FormID  pgtype.UUID `json:"form_id"`
	Column2 pgtype.UUID `json:"column_2"`
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTickets, arg.FormID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ResponseID,
			&i.RespondentEmail,
			&i.Answers,
			&i.StatusID,
			&i.AssigneeID,
			&i.Priority,
			&i.SubmittedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicket = `-- name: UpdateTicket :execrows
UPDATE tickets
SET status_id = $2,
    assignee_id = $3,
    priority = $4
WHERE id = $1
`

type UpdateTicketParams struct {
	ID         pgtype.UUID `json:"id"`
	StatusID   pgtype.UUID `json:"status_id"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
	Priority   string      `json:"priority"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTicket,
		arg.ID,
		arg.StatusID,
		arg.AssigneeID,
		arg.Priority,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
