// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ticket_histories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicketHistory = `-- name: CreateTicketHistory :one
INSERT INTO ticket_histories (id, ticket_id, changed_by, changed_by_name, field_name, old_value, new_value)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, ticket_id, changed_by, changed_by_name, field_name, old_value, new_value, created_at
`

type CreateTicketHistoryParams struct {
	ID            pgtype.UUID `json:"id"`
	TicketID      pgtype.UUID `json:"ticket_id"`
	ChangedBy     pgtype.UUID `json:"changed_by"`
	ChangedByName string      `json:"changed_by_name"`
	FieldName     string      `json:"field_name"`
	OldValue      pgtype.Text `json:"old_value"`
	NewValue      pgtype.Text `json:"new_value"`
}

func (q *Queries) CreateTicketHistory(ctx context.Context, arg CreateTicketHistoryParams) (TicketHistory, error) {
	row := q.db.QueryRow(ctx, createTicketHistory,
		arg.ID,
		arg.TicketID,
		arg.ChangedBy,
		arg.ChangedByName,
		arg.FieldName,
		arg.OldValue,
		arg.NewValue,
	)
	var i TicketHistory
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.ChangedBy,
		&i.ChangedByName,
		&i.FieldName,
		&i.OldValue,
		&i.NewValue,
		&i.CreatedAt,
	)
	return i, err
}

const listTicketHistoriesByTicket = `-- name: ListTicketHistoriesByTicket :many
SELECT id, ticket_id, changed_by, changed_by_name, field_name, old_value, new_value, created_at
FROM ticket_histories
WHERE ticket_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTicketHistoriesByTicket(ctx context.Context, ticketID pgtype.UUID) ([]TicketHistory, error) {
	rows, err := q.db.Query(ctx, listTicketHistoriesByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketHistory
	for rows.Next() {
		var i TicketHistory
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.ChangedBy,
			&i.ChangedByName,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
