// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: forms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFormTitleQuestion = `-- name: GetFormTitleQuestion :one
SELECT title_question_id FROM forms WHERE form_id = $1
`

func (q *Queries) GetFormTitleQuestion(ctx context.Context, formID string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getFormTitleQuestion, formID)
	var title_question_id pgtype.Text
	err := row.Scan(&title_question_id)
	return title_question_id, err
}

const updateFormTitleQuestion = `-- name: UpdateFormTitleQuestion :exec
UPDATE forms
SET title_question_id = $2
WHERE form_id = $1
`

type UpdateFormTitleQuestionParams struct {
	FormID          string      `json:"form_id"`
	TitleQuestionID pgtype.Text `json:"title_question_id"`
}

func (q *Queries) UpdateFormTitleQuestion(ctx context.Context, arg UpdateFormTitleQuestionParams) error {
	_, err := q.db.Exec(ctx, updateFormTitleQuestion, arg.FormID, arg.TitleQuestionID)
	return err
}
