// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: form_statuses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultFormStatus = `-- name: ClearDefaultFormStatus :exec
UPDATE form_statuses
SET is_default = FALSE
WHERE form_id = $1
  AND is_default = TRUE
`

func (q *Queries) ClearDefaultFormStatus(ctx context.Context, formID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultFormStatus, formID)
	return err
}

const createFormStatus = `-- name: CreateFormStatus :one
INSERT INTO form_statuses (id, form_id, name, color, display_order, is_default)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, form_id, name, color, display_order, is_default, created_at
`

type CreateFormStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	FormID       pgtype.UUID `json:"form_id"`
	Name         string      `json:"name"`
	Color        pgtype.Text `json:"color"`
	DisplayOrder int32       `json:"display_order"`
	IsDefault    bool        `json:"is_default"`
}

func (q *Queries) CreateFormStatus(ctx context.Context, arg CreateFormStatusParams) (FormStatus, error) {
	row := q.db.QueryRow(ctx, createFormStatus,
		arg.ID,
		arg.FormID,
		arg.Name,
		arg.Color,
		arg.DisplayOrder,
		arg.IsDefault,
	)
	var i FormStatus
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Name,
		&i.Color,
		&i.DisplayOrder,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFormStatus = `-- name: DeleteFormStatus :exec
DELETE FROM form_statuses
WHERE id = $1
`

func (q *Queries) DeleteFormStatus(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFormStatus, id)
	return err
}

const getDefaultFormStatus = `-- name: GetDefaultFormStatus :one
SELECT id, form_id, name, color, display_order, is_default, created_at
FROM form_statuses
WHERE form_id = $1
  AND is_default = TRUE
`

func (q *Queries) GetDefaultFormStatus(ctx context.Context, formID pgtype.UUID) (FormStatus, error) {
	row := q.db.QueryRow(ctx, getDefaultFormStatus, formID)
	var i FormStatus
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Name,
		&i.Color,
		&i.DisplayOrder,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getFormStatusByID = `-- name: GetFormStatusByID :one
SELECT id, form_id, name, color, display_order, is_default, created_at
FROM form_statuses
WHERE id = $1
`

func (q *Queries) GetFormStatusByID(ctx context.Context, id pgtype.UUID) (FormStatus, error) {
	row := q.db.QueryRow(ctx, getFormStatusByID, id)
	var i FormStatus
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Name,
		&i.Color,
		&i.DisplayOrder,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const listFormStatuses = `-- name: ListFormStatuses :many
SELECT id, form_id, name, color, display_order, is_default, created_at
FROM form_statuses
WHERE form_id = $1
ORDER BY display_order
`

func (q *Queries) ListFormStatuses(ctx context.Context, formID pgtype.UUID) ([]FormStatus, error) {
	rows, err := q.db.Query(ctx, listFormStatuses, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormStatus
	for rows.Next() {
		var i FormStatus
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Name,
			&i.Color,
			&i.DisplayOrder,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultFormStatus = `-- name: SetDefaultFormStatus :one
UPDATE form_statuses AS fs
SET is_default = TRUE
WHERE fs.id = $2
  AND fs.form_id = $1
RETURNING fs.id, fs.form_id, fs.name, fs.color, fs.display_order, fs.is_default, fs.created_at
`

type SetDefaultFormStatusParams struct {
	FormID pgtype.UUID `json:"form_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) SetDefaultFormStatus(ctx context.Context, arg SetDefaultFormStatusParams) (FormStatus, error) {
	row := q.db.QueryRow(ctx, setDefaultFormStatus, arg.FormID, arg.ID)
	var i FormStatus
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Name,
		&i.Color,
		&i.DisplayOrder,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const updateFormStatus = `-- name: UpdateFormStatus :one
UPDATE form_statuses
SET name = $2,
    color = $3,
    display_order = $4
WHERE id = $1
RETURNING id, form_id, name, color, display_order, is_default, created_at
`

type UpdateFormStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Color        pgtype.Text `json:"color"`
	DisplayOrder int32       `json:"display_order"`
}

func (q *Queries) UpdateFormStatus(ctx context.Context, arg UpdateFormStatusParams) (FormStatus, error) {
	row := q.db.QueryRow(ctx, updateFormStatus,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.DisplayOrder,
	)
	var i FormStatus
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Name,
		&i.Color,
		&i.DisplayOrder,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}
