// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: forms_sync.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFormSyncCursor = `-- name: GetFormSyncCursor :one
SELECT sync_cursor FROM forms WHERE form_id = $1
`

func (q *Queries) GetFormSyncCursor(ctx context.Context, formID string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getFormSyncCursor, formID)
	var sync_cursor pgtype.Timestamptz
	err := row.Scan(&sync_cursor)
	return sync_cursor, err
}

const updateSyncCursor = `-- name: UpdateSyncCursor :exec
UPDATE forms SET sync_cursor = $2 WHERE form_id = $1
`

type UpdateSyncCursorParams struct {
	FormID     string
	SyncCursor pgtype.Timestamptz
}

func (q *Queries) UpdateSyncCursor(ctx context.Context, arg UpdateSyncCursorParams) error {
	_, err := q.db.Exec(ctx, updateSyncCursor, arg.FormID, arg.SyncCursor)
	return err
}
