// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFormInvite = `-- name: CreateFormInvite :one
INSERT INTO form_invites (code, form_id, role, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING code, form_id, role, expires_at, created_by, created_at, revoked
`

type CreateFormInviteParams struct {
	Code      string             `json:"code"`
	FormID    string             `json:"form_id"`
	Role      string             `json:"role"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateFormInvite(ctx context.Context, arg CreateFormInviteParams) (FormInvite, error) {
	row := q.db.QueryRow(ctx, createFormInvite,
		arg.Code,
		arg.FormID,
		arg.Role,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i FormInvite
	err := row.Scan(
		&i.Code,
		&i.FormID,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Revoked,
	)
	return i, err
}

const getFormInviteForUpdate = `-- name: GetFormInviteForUpdate :one
SELECT code, form_id, role, expires_at, created_by, created_at, revoked
FROM form_invites
WHERE code = $1
FOR UPDATE
`

func (q *Queries) GetFormInviteForUpdate(ctx context.Context, code string) (FormInvite, error) {
	row := q.db.QueryRow(ctx, getFormInviteForUpdate, code)
	var i FormInvite
	err := row.Scan(
		&i.Code,
		&i.FormID,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Revoked,
	)
	return i, err
}

const listActiveFormInvites = `-- name: ListActiveFormInvites :many
SELECT code, form_id, role, expires_at, created_by, created_at, revoked
FROM form_invites
WHERE form_id = $1
  AND revoked = FALSE
  AND expires_at > $2
ORDER BY created_at DESC
`

type ListActiveFormInvitesParams struct {
	FormID    string             `json:"form_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListActiveFormInvites(ctx context.Context, arg ListActiveFormInvitesParams) ([]FormInvite, error) {
	rows, err := q.db.Query(ctx, listActiveFormInvites, arg.FormID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormInvite
	for rows.Next() {
		var i FormInvite
		if err := rows.Scan(
			&i.Code,
			&i.FormID,
			&i.Role,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeFormInvite = `-- name: RevokeFormInvite :one
UPDATE form_invites
SET revoked = TRUE
WHERE form_id = $1
  AND code = $2
RETURNING code, form_id, role, expires_at, created_by, created_at, revoked
`

type RevokeFormInviteParams struct {
	FormID string `json:"form_id"`
	Code   string `json:"code"`
}

func (q *Queries) RevokeFormInvite(ctx context.Context, arg RevokeFormInviteParams) (FormInvite, error) {
	row := q.db.QueryRow(ctx, revokeFormInvite, arg.FormID, arg.Code)
	var i FormInvite
	err := row.Scan(
		&i.Code,
		&i.FormID,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Revoked,
	)
	return i, err
}
