// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Form struct {
	FormID      string
	Title       string
	ConnectedAt pgtype.Timestamptz
	Description pgtype.Text
	PollingSec  pgtype.Int4
	SyncCursor  pgtype.Timestamptz
	Enabled     bool
}

type Response struct {
	ResponseID    string
	FormID        string
	SubmittedAt   pgtype.Timestamptz
	Payload       []byte
	SchemaVersion int32
	CreatedAt     pgtype.Timestamptz
}

type Ticket struct {
	ID         pgtype.UUID
	FormID     string
	ResponseID string
	Status     string
	AssigneeID pgtype.UUID
	Priority   int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type UserFormRole struct {
	UserID pgtype.UUID
	FormID string
	Role   string
}
