// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Form struct {
	FormID      string
	Title       string
	ConnectedAt pgtype.Timestamptz
	Description pgtype.Text
	PollingSec  pgtype.Int4
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type UserFormRole struct {
	UserID pgtype.UUID
	FormID string
	Role   string
}
