// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: responses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getResponseExists = `-- name: GetResponseExists :one
SELECT EXISTS(SELECT 1 FROM responses WHERE response_id = $1) AS exists
`

func (q *Queries) GetResponseExists(ctx context.Context, responseID string) (bool, error) {
	row := q.db.QueryRow(ctx, getResponseExists, responseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertResponse = `-- name: InsertResponse :execrows
INSERT INTO responses (response_id, form_id, submitted_at, payload, schema_version)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (response_id) DO NOTHING
`

type InsertResponseParams struct {
	ResponseID    string
	FormID        string
	SubmittedAt   pgtype.Timestamptz
	Payload       []byte
	SchemaVersion int32
}

func (q *Queries) InsertResponse(ctx context.Context, arg InsertResponseParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertResponse,
		arg.ResponseID,
		arg.FormID,
		arg.SubmittedAt,
		arg.Payload,
		arg.SchemaVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listResponses = `-- name: ListResponses :many
SELECT response_id, form_id, submitted_at, payload, schema_version, created_at
FROM responses
WHERE ($1::text IS NULL OR form_id = $1)
  AND ($2::timestamptz IS NULL OR submitted_at >= $2)
ORDER BY submitted_at DESC
LIMIT 200
`

type ListResponsesParams struct {
	Column1 string
	Column2 pgtype.Timestamptz
}

func (q *Queries) ListResponses(ctx context.Context, arg ListResponsesParams) ([]Response, error) {
	rows, err := q.db.Query(ctx, listResponses, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Response
	for rows.Next() {
		var i Response
		if err := rows.Scan(
			&i.ResponseID,
			&i.FormID,
			&i.SubmittedAt,
			&i.Payload,
			&i.SchemaVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
