// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFormAdmins = `-- name: CountFormAdmins :one
SELECT COUNT(*)
FROM user_form_roles
WHERE form_id = $1
  AND role = 'admin'
`

func (q *Queries) CountFormAdmins(ctx context.Context, formID string) (int64, error) {
	row := q.db.QueryRow(ctx, countFormAdmins, formID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserFormRole = `-- name: DeleteUserFormRole :exec
DELETE FROM user_form_roles WHERE user_id=$1 AND form_id=$2
`

type DeleteUserFormRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	FormID string      `json:"form_id"`
}

func (q *Queries) DeleteUserFormRole(ctx context.Context, arg DeleteUserFormRoleParams) error {
	_, err := q.db.Exec(ctx, deleteUserFormRole, arg.UserID, arg.FormID)
	return err
}

const getUserFormRole = `-- name: GetUserFormRole :one
SELECT role FROM user_form_roles WHERE user_id = $1 AND form_id = $2
`

type GetUserFormRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	FormID string      `json:"form_id"`
}

func (q *Queries) GetUserFormRole(ctx context.Context, arg GetUserFormRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserFormRole, arg.UserID, arg.FormID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listFormMembers = `-- name: ListFormMembers :many
SELECT u.id, u.email, u.display_name, u.created_at, r.role
FROM user_form_roles r
JOIN users u ON u.id = r.user_id
AND u.deletedAt IS NULL
WHERE r.form_id = $1
ORDER BY u.email
`

type ListFormMembersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Role        string             `json:"role"`
}

func (q *Queries) ListFormMembers(ctx context.Context, formID string) ([]ListFormMembersRow, error) {
	rows, err := q.db.Query(ctx, listFormMembers, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormMembersRow
	for rows.Next() {
		var i ListFormMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAccessibleForms = `-- name: ListUserAccessibleForms :many
SELECT f.form_id, f.title
FROM user_form_roles r JOIN forms f ON f.form_id = r.form_id
WHERE r.user_id = $1
ORDER BY f.title
`

type ListUserAccessibleFormsRow struct {
	FormID string `json:"form_id"`
	Title  string `json:"title"`
}

func (q *Queries) ListUserAccessibleForms(ctx context.Context, userID pgtype.UUID) ([]ListUserAccessibleFormsRow, error) {
	rows, err := q.db.Query(ctx, listUserAccessibleForms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserAccessibleFormsRow
	for rows.Next() {
		var i ListUserAccessibleFormsRow
		if err := rows.Scan(&i.FormID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserFormRole = `-- name: UpsertUserFormRole :exec
INSERT INTO user_form_roles(user_id, form_id, role)
VALUES ($1,$2,$3)
ON CONFLICT (user_id, form_id) DO UPDATE SET role = EXCLUDED.role
`

type UpsertUserFormRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	FormID string      `json:"form_id"`
	Role   string      `json:"role"`
}

func (q *Queries) UpsertUserFormRole(ctx context.Context, arg UpsertUserFormRoleParams) error {
	_, err := q.db.Exec(ctx, upsertUserFormRole, arg.UserID, arg.FormID, arg.Role)
	return err
}
