// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserFormRole = `-- name: DeleteUserFormRole :exec
DELETE FROM user_form_roles WHERE user_id=$1 AND form_id=$2
`

type DeleteUserFormRoleParams struct {
	UserID pgtype.UUID
	FormID string
}

func (q *Queries) DeleteUserFormRole(ctx context.Context, arg DeleteUserFormRoleParams) error {
	_, err := q.db.Exec(ctx, deleteUserFormRole, arg.UserID, arg.FormID)
	return err
}

const getUserFormRole = `-- name: GetUserFormRole :one
SELECT role FROM user_form_roles WHERE user_id = $1 AND form_id = $2
`

type GetUserFormRoleParams struct {
	UserID pgtype.UUID
	FormID string
}

func (q *Queries) GetUserFormRole(ctx context.Context, arg GetUserFormRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserFormRole, arg.UserID, arg.FormID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listFormMembers = `-- name: ListFormMembers :many
SELECT u.id, u.email, u.created_at, r.role
FROM user_form_roles r JOIN users u ON u.id = r.user_id
WHERE r.form_id = $1
ORDER BY u.email
`

type ListFormMembersRow struct {
	ID        pgtype.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
	Role      string
}

func (q *Queries) ListFormMembers(ctx context.Context, formID string) ([]ListFormMembersRow, error) {
	rows, err := q.db.Query(ctx, listFormMembers, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormMembersRow
	for rows.Next() {
		var i ListFormMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserFormRole = `-- name: UpsertUserFormRole :exec
INSERT INTO user_form_roles(user_id, form_id, role)
VALUES ($1,$2,$3)
ON CONFLICT (user_id, form_id) DO UPDATE SET role = EXCLUDED.role
`

type UpsertUserFormRoleParams struct {
	UserID pgtype.UUID
	FormID string
	Role   string
}

func (q *Queries) UpsertUserFormRole(ctx context.Context, arg UpsertUserFormRoleParams) error {
	_, err := q.db.Exec(ctx, upsertUserFormRole, arg.UserID, arg.FormID, arg.Role)
	return err
}
