// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (id, form_id, response_id, status, assignee_id)
VALUES ($1,$2,$3,'new',NULL)
RETURNING id, form_id, response_id, status, assignee_id, priority, created_at, updated_at
`

type CreateTicketParams struct {
	ID         pgtype.UUID
	FormID     string
	ResponseID string
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket, arg.ID, arg.FormID, arg.ResponseID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ResponseID,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, form_id, response_id, status, assignee_id, priority, created_at, updated_at
FROM tickets WHERE id = $1
`

func (q *Queries) GetTicket(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ResponseID,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTickets = `-- name: ListTickets :many
SELECT id, form_id, response_id, status, assignee_id, priority, created_at, updated_at
FROM tickets
WHERE ($1::text IS NULL OR form_id = $1)
  AND ($2::ticket_status IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT 200
`

type ListTicketsParams struct {
	Column1 string
	Column2 string
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTickets, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ResponseID,
			&i.Status,
			&i.AssigneeID,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets
SET status = COALESCE($2,status),
    assignee_id = COALESCE($3,assignee_id),
    updated_at = NOW()
WHERE id = $1
RETURNING id, form_id, response_id, status, assignee_id, priority, created_at, updated_at
`

type UpdateTicketParams struct {
	ID         pgtype.UUID
	Status     string
	AssigneeID pgtype.UUID
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicket, arg.ID, arg.Status, arg.AssigneeID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ResponseID,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
