// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTicketsByStatus = `-- name: CountTicketsByStatus :one
SELECT COUNT(1)
FROM tickets
WHERE status_id = $1
`

func (q *Queries) CountTicketsByStatus(ctx context.Context, statusID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTicketsByStatus, statusID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTicket = `-- name: CreateTicket :execrows
INSERT INTO tickets (id, form_id, response_id, respondent_email, answers, status_id, assignee_id, priority, submitted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (form_id, response_id) DO NOTHING
`

type CreateTicketParams struct {
	ID              pgtype.UUID        `json:"id"`
	FormID          pgtype.UUID        `json:"form_id"`
	ResponseID      string             `json:"response_id"`
	RespondentEmail pgtype.Text        `json:"respondent_email"`
	Answers         []byte             `json:"answers"`
	StatusID        pgtype.UUID        `json:"status_id"`
	AssigneeID      pgtype.UUID        `json:"assignee_id"`
	Priority        string             `json:"priority"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (int64, error) {
	result, err := q.db.Exec(ctx, createTicket,
		arg.ID,
		arg.FormID,
		arg.ResponseID,
		arg.RespondentEmail,
		arg.Answers,
		arg.StatusID,
		arg.AssigneeID,
		arg.Priority,
		arg.SubmittedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTicket = `-- name: GetTicket :one
SELECT t.id,
       t.form_id,
       t.response_id,
       t.respondent_email,
       t.answers,
       t.status_id,
       t.assignee_id,
       t.priority,
       t.submitted_at,
       t.created_at,
       f.title AS form_title,
       f.title_question_id,
       s.name AS status_name,
       s.color AS status_color,
       a.display_name AS assignee_display_name,
       a.email AS assignee_email
FROM tickets t
JOIN forms f ON f.id = t.form_id
JOIN form_statuses s ON s.id = t.status_id
LEFT JOIN users a ON a.id = t.assignee_id
WHERE t.id = $1
`

type GetTicketRow struct {
	ID                  pgtype.UUID        `json:"id"`
	FormID              pgtype.UUID        `json:"form_id"`
	ResponseID          string             `json:"response_id"`
	RespondentEmail     pgtype.Text        `json:"respondent_email"`
	Answers             []byte             `json:"answers"`
	StatusID            pgtype.UUID        `json:"status_id"`
	AssigneeID          pgtype.UUID        `json:"assignee_id"`
	Priority            string             `json:"priority"`
	SubmittedAt         pgtype.Timestamptz `json:"submitted_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	FormTitle           string             `json:"form_title"`
	TitleQuestionID     pgtype.Text        `json:"title_question_id"`
	StatusName          string             `json:"status_name"`
	StatusColor         pgtype.Text        `json:"status_color"`
	AssigneeDisplayName pgtype.Text        `json:"assignee_display_name"`
	AssigneeEmail       pgtype.Text        `json:"assignee_email"`
}

func (q *Queries) GetTicket(ctx context.Context, id pgtype.UUID) (GetTicketRow, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i GetTicketRow
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ResponseID,
		&i.RespondentEmail,
		&i.Answers,
		&i.StatusID,
		&i.AssigneeID,
		&i.Priority,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.FormTitle,
		&i.TitleQuestionID,
		&i.StatusName,
		&i.StatusColor,
		&i.AssigneeDisplayName,
		&i.AssigneeEmail,
	)
	return i, err
}

const listTickets = `-- name: ListTickets :many
SELECT t.id,
       t.form_id,
       t.response_id,
       t.respondent_email,
       t.answers,
       t.status_id,
       t.assignee_id,
       t.priority,
       t.submitted_at,
       t.created_at,
       f.title AS form_title,
       f.title_question_id,
       s.name AS status_name,
       s.color AS status_color,
       a.display_name AS assignee_display_name,
       a.email AS assignee_email
FROM tickets t
JOIN forms f ON f.id = t.form_id
JOIN form_statuses s ON s.id = t.status_id
LEFT JOIN users a ON a.id = t.assignee_id
WHERE ($1::uuid IS NULL OR t.form_id = $1)
  AND ($2::uuid IS NULL OR t.status_id = $2)
ORDER BY t.created_at DESC
LIMIT 200
`

type ListTicketsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
}

type ListTicketsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	FormID              pgtype.UUID        `json:"form_id"`
	ResponseID          string             `json:"response_id"`
	RespondentEmail     pgtype.Text        `json:"respondent_email"`
	Answers             []byte             `json:"answers"`
	StatusID            pgtype.UUID        `json:"status_id"`
	AssigneeID          pgtype.UUID        `json:"assignee_id"`
	Priority            string             `json:"priority"`
	SubmittedAt         pgtype.Timestamptz `json:"submitted_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	FormTitle           string             `json:"form_title"`
	TitleQuestionID     pgtype.Text        `json:"title_question_id"`
	StatusName          string             `json:"status_name"`
	StatusColor         pgtype.Text        `json:"status_color"`
	AssigneeDisplayName pgtype.Text        `json:"assignee_display_name"`
	AssigneeEmail       pgtype.Text        `json:"assignee_email"`
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]ListTicketsRow, error) {
	rows, err := q.db.Query(ctx, listTickets, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketsRow
	for rows.Next() {
		var i ListTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ResponseID,
			&i.RespondentEmail,
			&i.Answers,
			&i.StatusID,
			&i.AssigneeID,
			&i.Priority,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.FormTitle,
			&i.TitleQuestionID,
			&i.StatusName,
			&i.StatusColor,
			&i.AssigneeDisplayName,
			&i.AssigneeEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketAssignee = `-- name: UpdateTicketAssignee :one
UPDATE tickets
SET assignee_id = $2
WHERE id = $1
RETURNING id, form_id, response_id, respondent_email, answers, status_id, assignee_id, priority, submitted_at, created_at
`

type UpdateTicketAssigneeParams struct {
	ID         pgtype.UUID `json:"id"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
}

func (q *Queries) UpdateTicketAssignee(ctx context.Context, arg UpdateTicketAssigneeParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketAssignee, arg.ID, arg.AssigneeID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ResponseID,
		&i.RespondentEmail,
		&i.Answers,
		&i.StatusID,
		&i.AssigneeID,
		&i.Priority,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateTicketPriority = `-- name: UpdateTicketPriority :one
UPDATE tickets
SET priority = $2
WHERE id = $1
RETURNING id, form_id, response_id, respondent_email, answers, status_id, assignee_id, priority, submitted_at, created_at
`

type UpdateTicketPriorityParams struct {
	ID       pgtype.UUID `json:"id"`
	Priority string      `json:"priority"`
}

func (q *Queries) UpdateTicketPriority(ctx context.Context, arg UpdateTicketPriorityParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketPriority, arg.ID, arg.Priority)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ResponseID,
		&i.RespondentEmail,
		&i.Answers,
		&i.StatusID,
		&i.AssigneeID,
		&i.Priority,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateTicketStatus = `-- name: UpdateTicketStatus :one
UPDATE tickets
SET status_id = $2
WHERE id = $1
RETURNING id, form_id, response_id, respondent_email, answers, status_id, assignee_id, priority, submitted_at, created_at
`

type UpdateTicketStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	StatusID pgtype.UUID `json:"status_id"`
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketStatus, arg.ID, arg.StatusID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ResponseID,
		&i.RespondentEmail,
		&i.Answers,
		&i.StatusID,
		&i.AssigneeID,
		&i.Priority,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}
