// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (id, form_id, response_id, status, assignee_id)
VALUES ($1,$2,$3,'new',NULL)
RETURNING id, form_id, response_id, status, assignee_id, priority, created_at, updated_at
`

type CreateTicketParams struct {
	ID         pgtype.UUID `json:"id"`
	FormID     string      `json:"form_id"`
	ResponseID string      `json:"response_id"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket, arg.ID, arg.FormID, arg.ResponseID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ResponseID,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT t.id,
       t.form_id,
       t.response_id,
       t.status,
       t.assignee_id,
       t.priority,
       t.created_at,
       t.updated_at,
       f.title AS form_title,
       f.title_question_id,
       r.submitted_at,
       r.payload,
       a.display_name AS assignee_display_name,
       a.email AS assignee_email
FROM tickets t
JOIN forms f ON f.form_id = t.form_id
JOIN responses r ON r.response_id = t.response_id
LEFT JOIN users a ON a.id = t.assignee_id
WHERE t.id = $1
`

type GetTicketRow struct {
	ID                  pgtype.UUID        `json:"id"`
	FormID              string             `json:"form_id"`
	ResponseID          string             `json:"response_id"`
	Status              string             `json:"status"`
	AssigneeID          pgtype.UUID        `json:"assignee_id"`
	Priority            int32              `json:"priority"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	FormTitle           string             `json:"form_title"`
	TitleQuestionID     pgtype.Text        `json:"title_question_id"`
	SubmittedAt         pgtype.Timestamptz `json:"submitted_at"`
	Payload             []byte             `json:"payload"`
	AssigneeDisplayName pgtype.Text        `json:"assignee_display_name"`
	AssigneeEmail       pgtype.Text        `json:"assignee_email"`
}

func (q *Queries) GetTicket(ctx context.Context, id pgtype.UUID) (GetTicketRow, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i GetTicketRow
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ResponseID,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FormTitle,
		&i.TitleQuestionID,
		&i.SubmittedAt,
		&i.Payload,
		&i.AssigneeDisplayName,
		&i.AssigneeEmail,
	)
	return i, err
}

const listTickets = `-- name: ListTickets :many
SELECT t.id,
       t.form_id,
       t.response_id,
       t.status,
       t.assignee_id,
       t.priority,
       t.created_at,
       t.updated_at,
       f.title AS form_title,
       f.title_question_id,
       r.submitted_at,
       r.payload,
       a.display_name AS assignee_display_name,
       a.email AS assignee_email
FROM tickets t
JOIN forms f ON f.form_id = t.form_id
JOIN responses r ON r.response_id = t.response_id
LEFT JOIN users a ON a.id = t.assignee_id
WHERE ($1::text IS NULL OR t.form_id = $1)
  AND ($2::text = '' OR $2::text IS NULL OR t.status = $2::ticket_status)
ORDER BY t.created_at DESC
LIMIT 200
`

type ListTicketsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

type ListTicketsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	FormID              string             `json:"form_id"`
	ResponseID          string             `json:"response_id"`
	Status              string             `json:"status"`
	AssigneeID          pgtype.UUID        `json:"assignee_id"`
	Priority            int32              `json:"priority"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	FormTitle           string             `json:"form_title"`
	TitleQuestionID     pgtype.Text        `json:"title_question_id"`
	SubmittedAt         pgtype.Timestamptz `json:"submitted_at"`
	Payload             []byte             `json:"payload"`
	AssigneeDisplayName pgtype.Text        `json:"assignee_display_name"`
	AssigneeEmail       pgtype.Text        `json:"assignee_email"`
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]ListTicketsRow, error) {
	rows, err := q.db.Query(ctx, listTickets, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketsRow
	for rows.Next() {
		var i ListTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ResponseID,
			&i.Status,
			&i.AssigneeID,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FormTitle,
			&i.TitleQuestionID,
			&i.SubmittedAt,
			&i.Payload,
			&i.AssigneeDisplayName,
			&i.AssigneeEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets
SET status = COALESCE($1::ticket_status, status),
    assignee_id = CASE
        WHEN $2::bool THEN NULL
        WHEN $3::uuid IS NOT NULL THEN $3::uuid
        ELSE assignee_id
    END,
    priority = COALESCE($4, priority),
    updated_at = NOW()
WHERE id = $5
RETURNING id, form_id, response_id, status, assignee_id, priority, created_at, updated_at
`

type UpdateTicketParams struct {
	Status        interface{} `json:"status"`
	ClearAssignee bool        `json:"clear_assignee"`
	AssigneeID    pgtype.UUID `json:"assignee_id"`
	Priority      pgtype.Int4 `json:"priority"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicket,
		arg.Status,
		arg.ClearAssignee,
		arg.AssigneeID,
		arg.Priority,
		arg.ID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ResponseID,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
