// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash) VALUES ($1, $2, $3)
RETURNING id, email, password_hash, created_at
`

type CreateUserParams struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at FROM users WHERE email=$1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserFormRole = `-- name: GetUserFormRole :one
SELECT role FROM user_form_roles WHERE user_id = $1 AND form_id = $2
`

type GetUserFormRoleParams struct {
	UserID pgtype.UUID
	FormID string
}

func (q *Queries) GetUserFormRole(ctx context.Context, arg GetUserFormRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserFormRole, arg.UserID, arg.FormID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listForms = `-- name: ListForms :many
SELECT form_id, title FROM forms
`

type ListFormsRow struct {
	FormID string
	Title  string
}

func (q *Queries) ListForms(ctx context.Context) ([]ListFormsRow, error) {
	rows, err := q.db.Query(ctx, listForms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormsRow
	for rows.Next() {
		var i ListFormsRow
		if err := rows.Scan(&i.FormID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertForm = `-- name: UpsertForm :exec
INSERT INTO forms (form_id, title, description, polling_sec)
VALUES ($1, $2, $3, $4)
ON CONFLICT (form_id) DO UPDATE
SET title = EXCLUDED.title, description = EXCLUDED.description, polling_sec = EXCLUDED.polling_sec
`

type UpsertFormParams struct {
	FormID      string
	Title       string
	Description pgtype.Text
	PollingSec  pgtype.Int4
}

func (q *Queries) UpsertForm(ctx context.Context, arg UpsertFormParams) error {
	_, err := q.db.Exec(ctx, upsertForm,
		arg.FormID,
		arg.Title,
		arg.Description,
		arg.PollingSec,
	)
	return err
}

const upsertUserFormRole = `-- name: UpsertUserFormRole :exec
INSERT INTO user_form_roles (user_id, form_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, form_id) DO UPDATE
SET role = EXCLUDED.role
`

type UpsertUserFormRoleParams struct {
	UserID pgtype.UUID
	FormID string
	Role   string
}

func (q *Queries) UpsertUserFormRole(ctx context.Context, arg UpsertUserFormRoleParams) error {
	_, err := q.db.Exec(ctx, upsertUserFormRole, arg.UserID, arg.FormID, arg.Role)
	return err
}
