import type { FormResponse, ChatMessage, User } from "@/types/form-response"

export const mockUsers: User[] = [
  { id: "1", name: "田中 太郎", email: "tanaka@example.com" },
  { id: "2", name: "佐藤 花子", email: "sato@example.com" },
  { id: "3", name: "鈴木 一郎", email: "suzuki@example.com" },
]

export const mockFormResponses: FormResponse[] = [
  {
    id: "resp-1",
    formId: "form-001",
    formTitle: "新規お問い合わせフォーム",
    respondentEmail: "customer1@example.com",
    respondentName: "山田 次郎",
    submittedAt: new Date("2024-01-15T10:30:00"),
    status: "new",
    assignedTo: null,
    priority: "high",
    responses: {
      q1: "製品Aについて",
      q2: "価格とスペックの詳細を知りたいです",
      q3: "法人",
    },
  },
  {
    id: "resp-2",
    formId: "form-001",
    formTitle: "新規お問い合わせフォーム",
    respondentEmail: "customer2@example.com",
    respondentName: "伊藤 美咲",
    submittedAt: new Date("2024-01-14T14:20:00"),
    status: "in-review",
    assignedTo: "1",
    priority: "medium",
    responses: {
      q1: "製品Bについて",
      q2: "導入事例を教えてください",
      q3: "個人",
    },
  },
  {
    id: "resp-3",
    formId: "form-002",
    formTitle: "サポートリクエスト",
    respondentEmail: "customer3@example.com",
    respondentName: "高橋 健太",
    submittedAt: new Date("2024-01-13T09:15:00"),
    status: "needs-info",
    assignedTo: "2",
    priority: "high",
    responses: {
      q1: "ログインできない",
      q2: "パスワードをリセットしても解決しません",
      q3: "緊急",
    },
  },
  {
    id: "resp-4",
    formId: "form-001",
    formTitle: "新規お問い合わせフォーム",
    respondentEmail: "customer4@example.com",
    respondentName: "中村 直美",
    submittedAt: new Date("2024-01-12T16:45:00"),
    status: "completed",
    assignedTo: "1",
    priority: "low",
    responses: {
      q1: "製品Cについて",
      q2: "資料請求",
      q3: "法人",
    },
  },
  {
    id: "resp-5",
    formId: "form-002",
    formTitle: "サポートリクエスト",
    respondentEmail: "customer5@example.com",
    respondentName: "小林 誠",
    submittedAt: new Date("2024-01-16T11:00:00"),
    status: "new",
    assignedTo: null,
    priority: "medium",
    responses: {
      q1: "機能追加の要望",
      q2: "エクスポート機能が欲しい",
      q3: "通常",
    },
  },
]

export const mockChatMessages: ChatMessage[] = [
  {
    id: "msg-1",
    responseId: "resp-2",
    senderId: "1",
    senderName: "田中 太郎",
    senderType: "staff",
    message: "お問い合わせありがとうございます。製品Bの導入事例について、業種を教えていただけますか？",
    timestamp: new Date("2024-01-14T15:00:00"),
    isRead: true,
  },
  {
    id: "msg-2",
    responseId: "resp-2",
    senderId: "customer2",
    senderName: "伊藤 美咲",
    senderType: "respondent",
    message: "IT業界です。特にSaaS企業の事例があれば教えてください。",
    timestamp: new Date("2024-01-14T15:30:00"),
    isRead: true,
  },
  {
    id: "msg-3",
    responseId: "resp-3",
    senderId: "2",
    senderName: "佐藤 花子",
    senderType: "staff",
    message: "ご不便をおかけしております。登録されているメールアドレスを確認させていただけますか？",
    timestamp: new Date("2024-01-13T10:00:00"),
    isRead: true,
  },
  {
    id: "msg-4",
    responseId: "resp-3",
    senderId: "customer3",
    senderName: "高橋 健太",
    senderType: "respondent",
    message: "customer3@example.comです。",
    timestamp: new Date("2024-01-13T10:15:00"),
    isRead: false,
  },
]
